package com.alpha.city;

public class Cities_3 {
	@SuppressWarnings("unchecked")
	public static void city_UAE() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abu Dhabi");
		com.alpha.login.SignUp.cityBox.addItem("Ajmān");
		com.alpha.login.SignUp.cityBox.addItem("Al Ain");
		com.alpha.login.SignUp.cityBox.addItem("Al Awdah");
		com.alpha.login.SignUp.cityBox.addItem("Al Fahlayn");
		com.alpha.login.SignUp.cityBox.addItem("Al Fulayyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Fara");
		com.alpha.login.SignUp.cityBox.addItem("Al Ghabah");
		com.alpha.login.SignUp.cityBox.addItem("Al Ghabam ");
		com.alpha.login.SignUp.cityBox.addItem("Al Ghashban");
		com.alpha.login.SignUp.cityBox.addItem("Al Hamraniyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Hamriyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Haybah");
		com.alpha.login.SignUp.cityBox.addItem("Al Hayl");
		com.alpha.login.SignUp.cityBox.addItem("Al Hayr");
		com.alpha.login.SignUp.cityBox.addItem("Al Hayrah");
		com.alpha.login.SignUp.cityBox.addItem("Al Hulaylah");
		com.alpha.login.SignUp.cityBox.addItem("Al Jaddah");
		com.alpha.login.SignUp.cityBox.addItem("Al Khari");
		com.alpha.login.SignUp.cityBox.addItem("Al Khashfah");
		com.alpha.login.SignUp.cityBox.addItem("Al Mahamm");
		com.alpha.login.SignUp.cityBox.addItem("Al Masafirah");
		com.alpha.login.SignUp.cityBox.addItem("Al Mataf");
		com.alpha.login.SignUp.cityBox.addItem("Al Mu'amurah");
		com.alpha.login.SignUp.cityBox.addItem("Al Naslah");
		com.alpha.login.SignUp.cityBox.addItem("Al Qir");
		com.alpha.login.SignUp.cityBox.addItem("Al Quwayz");
		com.alpha.login.SignUp.cityBox.addItem("Al Usayli");
		com.alpha.login.SignUp.cityBox.addItem("Al Yahar");
		com.alpha.login.SignUp.cityBox.addItem("Ar Rafa'ah");
		com.alpha.login.SignUp.cityBox.addItem("Arthaban");
		com.alpha.login.SignUp.cityBox.addItem("Athabat");
		com.alpha.login.SignUp.cityBox.addItem("Ash Sha'm");
		com.alpha.login.SignUp.cityBox.addItem("As Sur");
		com.alpha.login.SignUp.cityBox.addItem("Awanat");
		com.alpha.login.SignUp.cityBox.addItem("Ras al-Khaimah");
		com.alpha.login.SignUp.cityBox.addItem("Baqal");
		com.alpha.login.SignUp.cityBox.addItem("Bidiyah");
		com.alpha.login.SignUp.cityBox.addItem("Daftah");
		com.alpha.login.SignUp.cityBox.addItem("Dhadna");
		com.alpha.login.SignUp.cityBox.addItem("Dibba Al-Fujairah");
		com.alpha.login.SignUp.cityBox.addItem("Dibba Al-Hisn");
		com.alpha.login.SignUp.cityBox.addItem("Dubai");
		com.alpha.login.SignUp.cityBox.addItem("Fujairah");
		com.alpha.login.SignUp.cityBox.addItem("Kalba");
		com.alpha.login.SignUp.cityBox.addItem("Kawr Fakkān");
		com.alpha.login.SignUp.cityBox.addItem("Mīnā' Jabal 'Alī");
		com.alpha.login.SignUp.cityBox.addItem("Mīnā' Şaqr");
		com.alpha.login.SignUp.cityBox.addItem("Mīnā' Zāyid");
		com.alpha.login.SignUp.cityBox.addItem("Ras al-Khaimah");
		com.alpha.login.SignUp.cityBox.addItem("Umm al-Qaiwain");
		com.alpha.login.SignUp.cityBox.addItem("Quţūf");
		com.alpha.login.SignUp.cityBox.addItem("Ruwais");
		com.alpha.login.SignUp.cityBox.addItem("Sharjah");
		com.alpha.login.SignUp.cityBox.addItem("Sila");
		
		
	}
	@SuppressWarnings("unchecked")
	public static void city_England() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Birmingham");
		com.alpha.login.SignUp.cityBox.addItem("Bath");
		com.alpha.login.SignUp.cityBox.addItem("Birmingham");
		com.alpha.login.SignUp.cityBox.addItem("Bradford");
		com.alpha.login.SignUp.cityBox.addItem("Brighton and Hove");
		com.alpha.login.SignUp.cityBox.addItem("Bristol");
		com.alpha.login.SignUp.cityBox.addItem("Cardiff");
		com.alpha.login.SignUp.cityBox.addItem("Cambridge");
		com.alpha.login.SignUp.cityBox.addItem("Canterbury");
		com.alpha.login.SignUp.cityBox.addItem("Carlisle");
		com.alpha.login.SignUp.cityBox.addItem("Chester");
		com.alpha.login.SignUp.cityBox.addItem("Chelmsford");
		com.alpha.login.SignUp.cityBox.addItem("Chichester");
		com.alpha.login.SignUp.cityBox.addItem("Coventry");
		com.alpha.login.SignUp.cityBox.addItem("Derby");
		com.alpha.login.SignUp.cityBox.addItem("Durham");
		com.alpha.login.SignUp.cityBox.addItem("Ely");
		com.alpha.login.SignUp.cityBox.addItem("Exeter");
		com.alpha.login.SignUp.cityBox.addItem("Gloucester");
		com.alpha.login.SignUp.cityBox.addItem("Hereford");
		com.alpha.login.SignUp.cityBox.addItem("Kingston upon Hull");
		com.alpha.login.SignUp.cityBox.addItem("Lancaster");
		com.alpha.login.SignUp.cityBox.addItem("Leeds");
		com.alpha.login.SignUp.cityBox.addItem("Leicester");
		com.alpha.login.SignUp.cityBox.addItem("Lichfield");
		com.alpha.login.SignUp.cityBox.addItem("Lincoln");
		com.alpha.login.SignUp.cityBox.addItem("Liverpool");
		com.alpha.login.SignUp.cityBox.addItem("Manchester");
		com.alpha.login.SignUp.cityBox.addItem("Newcastle upon Tyne");
		com.alpha.login.SignUp.cityBox.addItem(" Norwich");
		com.alpha.login.SignUp.cityBox.addItem("Nottingham");
		com.alpha.login.SignUp.cityBox.addItem("Oxford");
		com.alpha.login.SignUp.cityBox.addItem("Peterborough");
		com.alpha.login.SignUp.cityBox.addItem("Plymouth");
		com.alpha.login.SignUp.cityBox.addItem("Portsmouth");
		com.alpha.login.SignUp.cityBox.addItem("Preston");
		com.alpha.login.SignUp.cityBox.addItem("Ripon");
		com.alpha.login.SignUp.cityBox.addItem("Salford");
		com.alpha.login.SignUp.cityBox.addItem("Salisbury");
		com.alpha.login.SignUp.cityBox.addItem("Sheffield");
		com.alpha.login.SignUp.cityBox.addItem("Southampton");
		com.alpha.login.SignUp.cityBox.addItem("St Albans");
		com.alpha.login.SignUp.cityBox.addItem("Stoke-on-Trent");
		com.alpha.login.SignUp.cityBox.addItem("Sunderland");
		com.alpha.login.SignUp.cityBox.addItem("Truro");
		com.alpha.login.SignUp.cityBox.addItem("Wakefield");
		com.alpha.login.SignUp.cityBox.addItem("Wells");
		com.alpha.login.SignUp.cityBox.addItem("Westminster");
		com.alpha.login.SignUp.cityBox.addItem("Winchester");
		com.alpha.login.SignUp.cityBox.addItem("Wolverhampton");
		com.alpha.login.SignUp.cityBox.addItem("Worcester");
		com.alpha.login.SignUp.cityBox.addItem("York");
		
	}
	@SuppressWarnings("unchecked")
	public static void city_Japan() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Nagoya");
		com.alpha.login.SignUp.cityBox.addItem("Toyohashi");
		com.alpha.login.SignUp.cityBox.addItem("Okazaki");
		com.alpha.login.SignUp.cityBox.addItem("Ichinomiya");
		com.alpha.login.SignUp.cityBox.addItem("Seto");
		com.alpha.login.SignUp.cityBox.addItem("Handa");
		com.alpha.login.SignUp.cityBox.addItem("Kasugai");
		com.alpha.login.SignUp.cityBox.addItem("Toyokawa");
		com.alpha.login.SignUp.cityBox.addItem("Tsushima");
		com.alpha.login.SignUp.cityBox.addItem("Hekinan");
		com.alpha.login.SignUp.cityBox.addItem("Kariya");
		com.alpha.login.SignUp.cityBox.addItem("Toyota");
		com.alpha.login.SignUp.cityBox.addItem("Anjō");
		com.alpha.login.SignUp.cityBox.addItem("Nishio");
		com.alpha.login.SignUp.cityBox.addItem("Gamagōri");
		com.alpha.login.SignUp.cityBox.addItem("Inuyama");
		com.alpha.login.SignUp.cityBox.addItem("Tokoname");
		com.alpha.login.SignUp.cityBox.addItem("Kōnan");
		com.alpha.login.SignUp.cityBox.addItem("Komaki");
		com.alpha.login.SignUp.cityBox.addItem("Inazawa");
		com.alpha.login.SignUp.cityBox.addItem("Tōkai");
		com.alpha.login.SignUp.cityBox.addItem("Ōbu");
		com.alpha.login.SignUp.cityBox.addItem("Chita");
		com.alpha.login.SignUp.cityBox.addItem("Chiryū");
		com.alpha.login.SignUp.cityBox.addItem("Owariasahi");
		com.alpha.login.SignUp.cityBox.addItem("Takahama");
		com.alpha.login.SignUp.cityBox.addItem("Iwakura");
		com.alpha.login.SignUp.cityBox.addItem("Toyoake");
		com.alpha.login.SignUp.cityBox.addItem("Nisshin");
		com.alpha.login.SignUp.cityBox.addItem("Tahara");
		com.alpha.login.SignUp.cityBox.addItem("Aisai");
		com.alpha.login.SignUp.cityBox.addItem("Aisai");
		com.alpha.login.SignUp.cityBox.addItem("Shinshiro");
		com.alpha.login.SignUp.cityBox.addItem("Kitanagoya");
		com.alpha.login.SignUp.cityBox.addItem("Yatomi");
		com.alpha.login.SignUp.cityBox.addItem("Miyoshi");
		com.alpha.login.SignUp.cityBox.addItem("Ama");
		com.alpha.login.SignUp.cityBox.addItem("Nagakute");
		com.alpha.login.SignUp.cityBox.addItem("Akita");
		com.alpha.login.SignUp.cityBox.addItem("Ōdate");
		com.alpha.login.SignUp.cityBox.addItem("Kazuno");
		com.alpha.login.SignUp.cityBox.addItem("Daisen");
		com.alpha.login.SignUp.cityBox.addItem("Katagami");
		com.alpha.login.SignUp.cityBox.addItem("Kitaakita");
		com.alpha.login.SignUp.cityBox.addItem("Oga");
		com.alpha.login.SignUp.cityBox.addItem("Yurihonjō");
		com.alpha.login.SignUp.cityBox.addItem("Yuzawa");
		com.alpha.login.SignUp.cityBox.addItem("Semboku	");
		com.alpha.login.SignUp.cityBox.addItem("Yokote");
		com.alpha.login.SignUp.cityBox.addItem("Nikaho");
		com.alpha.login.SignUp.cityBox.addItem("Noshiro");
		com.alpha.login.SignUp.cityBox.addItem("Hachinohe");
		com.alpha.login.SignUp.cityBox.addItem("Kuroishi");
		com.alpha.login.SignUp.cityBox.addItem("Misawa");
		com.alpha.login.SignUp.cityBox.addItem("Mutsu");
		com.alpha.login.SignUp.cityBox.addItem("Towada");
		com.alpha.login.SignUp.cityBox.addItem("Tsugaru");
		com.alpha.login.SignUp.cityBox.addItem("Goshogawara");
		com.alpha.login.SignUp.cityBox.addItem("Aomori");
		com.alpha.login.SignUp.cityBox.addItem("Hirakawa");
		com.alpha.login.SignUp.cityBox.addItem("Hirosaki");
		com.alpha.login.SignUp.cityBox.addItem("Chiba");
		com.alpha.login.SignUp.cityBox.addItem("Chōshi");
		com.alpha.login.SignUp.cityBox.addItem("Ichikawa");
		com.alpha.login.SignUp.cityBox.addItem("Funabashi");
		com.alpha.login.SignUp.cityBox.addItem("Tateyama");
		com.alpha.login.SignUp.cityBox.addItem("Kisarazu");
		com.alpha.login.SignUp.cityBox.addItem("Matsudo");
		com.alpha.login.SignUp.cityBox.addItem("Noda");
		com.alpha.login.SignUp.cityBox.addItem("Mobara");
		com.alpha.login.SignUp.cityBox.addItem("Narita");
		com.alpha.login.SignUp.cityBox.addItem("Sakura");
		com.alpha.login.SignUp.cityBox.addItem("Tōgane");
		com.alpha.login.SignUp.cityBox.addItem("Narashino");
		com.alpha.login.SignUp.cityBox.addItem("Kashiwa");
		com.alpha.login.SignUp.cityBox.addItem("Katsuura");
		com.alpha.login.SignUp.cityBox.addItem("Ichihara");
		com.alpha.login.SignUp.cityBox.addItem("Nagareyama");
		com.alpha.login.SignUp.cityBox.addItem("Yachiyo");
		com.alpha.login.SignUp.cityBox.addItem("Abiko");
		com.alpha.login.SignUp.cityBox.addItem("Kamagaya");
		com.alpha.login.SignUp.cityBox.addItem("Kimitsu");
		com.alpha.login.SignUp.cityBox.addItem("Futtsu");
		com.alpha.login.SignUp.cityBox.addItem("Urayasu");
		com.alpha.login.SignUp.cityBox.addItem("Yotsukaidō");
		com.alpha.login.SignUp.cityBox.addItem("Sodegaura");
		com.alpha.login.SignUp.cityBox.addItem("Yachimata");
		com.alpha.login.SignUp.cityBox.addItem("Inzai");
		com.alpha.login.SignUp.cityBox.addItem("Tomisato");
		com.alpha.login.SignUp.cityBox.addItem("Kamogawa");
		com.alpha.login.SignUp.cityBox.addItem("Asahi");
		com.alpha.login.SignUp.cityBox.addItem("Isumi");
		com.alpha.login.SignUp.cityBox.addItem("Sōsa");
		com.alpha.login.SignUp.cityBox.addItem("Minamibōsō");
		com.alpha.login.SignUp.cityBox.addItem("Katori");
		com.alpha.login.SignUp.cityBox.addItem("Sanmu");
		com.alpha.login.SignUp.cityBox.addItem("Oamishirasato");
		com.alpha.login.SignUp.cityBox.addItem("Matsuyama");
		com.alpha.login.SignUp.cityBox.addItem("Niihama");
		com.alpha.login.SignUp.cityBox.addItem("Shikokuchūō");
		com.alpha.login.SignUp.cityBox.addItem("Seiyo");
		com.alpha.login.SignUp.cityBox.addItem("Tōon");
		com.alpha.login.SignUp.cityBox.addItem("Saijō");
		com.alpha.login.SignUp.cityBox.addItem("Ōzu");
		com.alpha.login.SignUp.cityBox.addItem("Imabari");
		com.alpha.login.SignUp.cityBox.addItem("Yawatahama");
		com.alpha.login.SignUp.cityBox.addItem("Iyo");
		com.alpha.login.SignUp.cityBox.addItem("Uwajima");
		com.alpha.login.SignUp.cityBox.addItem("Fukui");
		com.alpha.login.SignUp.cityBox.addItem("Tsuruga");
		com.alpha.login.SignUp.cityBox.addItem("Obama");
		com.alpha.login.SignUp.cityBox.addItem("Ōno");
		com.alpha.login.SignUp.cityBox.addItem("Katsuyama");
		com.alpha.login.SignUp.cityBox.addItem("Sabae");
		com.alpha.login.SignUp.cityBox.addItem("Awara");
		com.alpha.login.SignUp.cityBox.addItem("Sakai");
		com.alpha.login.SignUp.cityBox.addItem("Fukuoka");
		com.alpha.login.SignUp.cityBox.addItem("Kurume");
		com.alpha.login.SignUp.cityBox.addItem("Ōmuta");
		com.alpha.login.SignUp.cityBox.addItem("Nōgata");
		com.alpha.login.SignUp.cityBox.addItem("Tagawa");
		com.alpha.login.SignUp.cityBox.addItem("Yanagawa");
		com.alpha.login.SignUp.cityBox.addItem("Yame");
		com.alpha.login.SignUp.cityBox.addItem("Chikugo");
		com.alpha.login.SignUp.cityBox.addItem("Chikugo");
		com.alpha.login.SignUp.cityBox.addItem("Yukuhashi");
		com.alpha.login.SignUp.cityBox.addItem("Buzen");
		com.alpha.login.SignUp.cityBox.addItem("Nakagawa");
		com.alpha.login.SignUp.cityBox.addItem("");
		com.alpha.login.SignUp.cityBox.addItem("Nakama");
		com.alpha.login.SignUp.cityBox.addItem("Kitakyushu");
		com.alpha.login.SignUp.cityBox.addItem("Ogōri");
		com.alpha.login.SignUp.cityBox.addItem("Chikushino");
		com.alpha.login.SignUp.cityBox.addItem("Kasuga");
		com.alpha.login.SignUp.cityBox.addItem("Kasuga");
		com.alpha.login.SignUp.cityBox.addItem("Munakata");
		com.alpha.login.SignUp.cityBox.addItem("Dazaifu");
		com.alpha.login.SignUp.cityBox.addItem("Koga");
		com.alpha.login.SignUp.cityBox.addItem("Fukutsu");
		com.alpha.login.SignUp.cityBox.addItem("Ukiha");
		com.alpha.login.SignUp.cityBox.addItem("Miyawaka");
		com.alpha.login.SignUp.cityBox.addItem("Asakura");
		com.alpha.login.SignUp.cityBox.addItem("Iizuka");
		com.alpha.login.SignUp.cityBox.addItem("Kama");
		com.alpha.login.SignUp.cityBox.addItem("Miyama");
		com.alpha.login.SignUp.cityBox.addItem("Itoshima");
		com.alpha.login.SignUp.cityBox.addItem("Aizuwakamatsu");
		com.alpha.login.SignUp.cityBox.addItem("Fukushima");
		com.alpha.login.SignUp.cityBox.addItem("Kōriyama");
		com.alpha.login.SignUp.cityBox.addItem("Sukagawa");
		com.alpha.login.SignUp.cityBox.addItem("Sōma");
		com.alpha.login.SignUp.cityBox.addItem("Iwaki");
		com.alpha.login.SignUp.cityBox.addItem("Tamura");
		com.alpha.login.SignUp.cityBox.addItem("Shirakawa");
		com.alpha.login.SignUp.cityBox.addItem("Nihonmatsu");
		com.alpha.login.SignUp.cityBox.addItem("Minamisōma");
		com.alpha.login.SignUp.cityBox.addItem("Date");
		com.alpha.login.SignUp.cityBox.addItem("Kitakata");
		com.alpha.login.SignUp.cityBox.addItem("Motomiya");
		com.alpha.login.SignUp.cityBox.addItem("Gifu");
		com.alpha.login.SignUp.cityBox.addItem("Ōgaki");
		com.alpha.login.SignUp.cityBox.addItem("Takayama");
		com.alpha.login.SignUp.cityBox.addItem("Tajimi");
		com.alpha.login.SignUp.cityBox.addItem("Seki");
		com.alpha.login.SignUp.cityBox.addItem("Nakatsugawa");
		com.alpha.login.SignUp.cityBox.addItem("Mino");
		com.alpha.login.SignUp.cityBox.addItem("Mizunami");
		com.alpha.login.SignUp.cityBox.addItem("Hashima");
		com.alpha.login.SignUp.cityBox.addItem("Minokamo");
		com.alpha.login.SignUp.cityBox.addItem("Toki");
		com.alpha.login.SignUp.cityBox.addItem("Kakamigahara");
		com.alpha.login.SignUp.cityBox.addItem("Kani");
		com.alpha.login.SignUp.cityBox.addItem("Yamagata");
		com.alpha.login.SignUp.cityBox.addItem("Mizuho");
		com.alpha.login.SignUp.cityBox.addItem("Hida");
		com.alpha.login.SignUp.cityBox.addItem("Motosu");
		com.alpha.login.SignUp.cityBox.addItem("Gujō");
		com.alpha.login.SignUp.cityBox.addItem("Gero");
		com.alpha.login.SignUp.cityBox.addItem("Ena");
		com.alpha.login.SignUp.cityBox.addItem("Kaizu");
		com.alpha.login.SignUp.cityBox.addItem("Maebashi");
		com.alpha.login.SignUp.cityBox.addItem("Takasaki");
		com.alpha.login.SignUp.cityBox.addItem("Kiryū");
		com.alpha.login.SignUp.cityBox.addItem("Isesaki");
		com.alpha.login.SignUp.cityBox.addItem("Ōta");
		com.alpha.login.SignUp.cityBox.addItem("Numata");
		com.alpha.login.SignUp.cityBox.addItem("Tatebayashi");
		com.alpha.login.SignUp.cityBox.addItem("Fujioka");
		com.alpha.login.SignUp.cityBox.addItem("Shibukawa");
		com.alpha.login.SignUp.cityBox.addItem("Annaka");
		com.alpha.login.SignUp.cityBox.addItem("Tomioka");
		com.alpha.login.SignUp.cityBox.addItem("Midori");
		com.alpha.login.SignUp.cityBox.addItem("Hiroshima");
		com.alpha.login.SignUp.cityBox.addItem("Onomichi");
		com.alpha.login.SignUp.cityBox.addItem("Kure");
		com.alpha.login.SignUp.cityBox.addItem("Fukuyama");
		com.alpha.login.SignUp.cityBox.addItem("Mihara");
		com.alpha.login.SignUp.cityBox.addItem("Fuchū");
		com.alpha.login.SignUp.cityBox.addItem("Miyoshi");
		com.alpha.login.SignUp.cityBox.addItem("Shōbara");
		com.alpha.login.SignUp.cityBox.addItem("Ōtake");
		com.alpha.login.SignUp.cityBox.addItem("Takehara");
		com.alpha.login.SignUp.cityBox.addItem("Higashihiroshima");
		com.alpha.login.SignUp.cityBox.addItem("Hatsukaichi");
		com.alpha.login.SignUp.cityBox.addItem("Akitakata");
		com.alpha.login.SignUp.cityBox.addItem("Etajima");
		com.alpha.login.SignUp.cityBox.addItem("Sapporo");
		com.alpha.login.SignUp.cityBox.addItem("Hakodate");
		com.alpha.login.SignUp.cityBox.addItem("Otaru");
		com.alpha.login.SignUp.cityBox.addItem("Asahikawa");
		com.alpha.login.SignUp.cityBox.addItem("Muroran");
		com.alpha.login.SignUp.cityBox.addItem("Obihiro");
		com.alpha.login.SignUp.cityBox.addItem("Yūbari");
		com.alpha.login.SignUp.cityBox.addItem("Iwamizawa");
		com.alpha.login.SignUp.cityBox.addItem("Abashiri");
		com.alpha.login.SignUp.cityBox.addItem("Rumoi");
		com.alpha.login.SignUp.cityBox.addItem("Tomakomai");
		com.alpha.login.SignUp.cityBox.addItem("Wakkanai");
		com.alpha.login.SignUp.cityBox.addItem("Bibai");
		com.alpha.login.SignUp.cityBox.addItem("Ashibetsu");
		com.alpha.login.SignUp.cityBox.addItem("Ebetsu");
		com.alpha.login.SignUp.cityBox.addItem("Akabira");
		com.alpha.login.SignUp.cityBox.addItem("Monbetsu");
		com.alpha.login.SignUp.cityBox.addItem("Mikasa");
		com.alpha.login.SignUp.cityBox.addItem("Nemuro");
		com.alpha.login.SignUp.cityBox.addItem("Chitose");
		com.alpha.login.SignUp.cityBox.addItem("Takikawa");
		com.alpha.login.SignUp.cityBox.addItem("Sunagawa");
		com.alpha.login.SignUp.cityBox.addItem("Utashinai");
		com.alpha.login.SignUp.cityBox.addItem("Fukagawa");
		com.alpha.login.SignUp.cityBox.addItem("Furano");
		com.alpha.login.SignUp.cityBox.addItem("Noboribetsu");
		com.alpha.login.SignUp.cityBox.addItem("Eniwa");
		com.alpha.login.SignUp.cityBox.addItem("Date");
		com.alpha.login.SignUp.cityBox.addItem("Kitahiroshima");
		com.alpha.login.SignUp.cityBox.addItem("Ishikari");
		com.alpha.login.SignUp.cityBox.addItem("Shibetsu");
		com.alpha.login.SignUp.cityBox.addItem("Kushiro");
		com.alpha.login.SignUp.cityBox.addItem("Hokuto");
		com.alpha.login.SignUp.cityBox.addItem("Kitami");
		com.alpha.login.SignUp.cityBox.addItem("Nayoro");
		com.alpha.login.SignUp.cityBox.addItem("Kobe");
		com.alpha.login.SignUp.cityBox.addItem("Himeji");
		com.alpha.login.SignUp.cityBox.addItem("Amagasaki");
		com.alpha.login.SignUp.cityBox.addItem("Akashi");
		com.alpha.login.SignUp.cityBox.addItem("Nishinomiya");
		com.alpha.login.SignUp.cityBox.addItem("Aioi");
		com.alpha.login.SignUp.cityBox.addItem("Toyook");
		com.alpha.login.SignUp.cityBox.addItem("Kakogawa");
		com.alpha.login.SignUp.cityBox.addItem("Akō");
		com.alpha.login.SignUp.cityBox.addItem("Takarazuka");
		com.alpha.login.SignUp.cityBox.addItem("Takasago");
		com.alpha.login.SignUp.cityBox.addItem("Miki");
		com.alpha.login.SignUp.cityBox.addItem("Kawanishi");
		com.alpha.login.SignUp.cityBox.addItem("Ono");
		com.alpha.login.SignUp.cityBox.addItem("Sanda");
		com.alpha.login.SignUp.cityBox.addItem("Kasai");
		com.alpha.login.SignUp.cityBox.addItem("Sasayama");
		com.alpha.login.SignUp.cityBox.addItem("Yabu");
		com.alpha.login.SignUp.cityBox.addItem("Tamba");
		com.alpha.login.SignUp.cityBox.addItem("Minamiawaji");
		com.alpha.login.SignUp.cityBox.addItem("Asago");
		com.alpha.login.SignUp.cityBox.addItem("Awaji");
		com.alpha.login.SignUp.cityBox.addItem("Shisō");
		com.alpha.login.SignUp.cityBox.addItem("Nishiwaki");
		com.alpha.login.SignUp.cityBox.addItem("Tatsuno");
		com.alpha.login.SignUp.cityBox.addItem("Sumoto");
		com.alpha.login.SignUp.cityBox.addItem("Katō");
		com.alpha.login.SignUp.cityBox.addItem("Mito");
		com.alpha.login.SignUp.cityBox.addItem("Hitachi");
		com.alpha.login.SignUp.cityBox.addItem("Tsuchiura");
		com.alpha.login.SignUp.cityBox.addItem("Yūki");
		com.alpha.login.SignUp.cityBox.addItem("Ryūgasaki");
		com.alpha.login.SignUp.cityBox.addItem("Shimotsuma");
		com.alpha.login.SignUp.cityBox.addItem("Jōsō");
		com.alpha.login.SignUp.cityBox.addItem("Hitachiōta");
		com.alpha.login.SignUp.cityBox.addItem("Takahagi");
		com.alpha.login.SignUp.cityBox.addItem("Kitaibaraki");
		com.alpha.login.SignUp.cityBox.addItem("Toride");
		com.alpha.login.SignUp.cityBox.addItem("Ushiku");
	}
	@SuppressWarnings("unchecked")
	public static void city_China() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Beijing");
		com.alpha.login.SignUp.cityBox.addItem("Chongqing");
		com.alpha.login.SignUp.cityBox.addItem("Tianjin");
		com.alpha.login.SignUp.cityBox.addItem("Guangzhou");
		com.alpha.login.SignUp.cityBox.addItem("Shenzhen");
		com.alpha.login.SignUp.cityBox.addItem("Chengdu");
		com.alpha.login.SignUp.cityBox.addItem("Nanjing");
		com.alpha.login.SignUp.cityBox.addItem("Wuhan");
		com.alpha.login.SignUp.cityBox.addItem("Hangzhou");
		com.alpha.login.SignUp.cityBox.addItem("Xi'an#*	Shaanxi");
		com.alpha.login.SignUp.cityBox.addItem("Dongguan");
		com.alpha.login.SignUp.cityBox.addItem("Foshan");
		com.alpha.login.SignUp.cityBox.addItem("Shenyang");
		com.alpha.login.SignUp.cityBox.addItem("Harbin");
		com.alpha.login.SignUp.cityBox.addItem("Qingdao");
		com.alpha.login.SignUp.cityBox.addItem("Dalian");
		com.alpha.login.SignUp.cityBox.addItem("Jinan");
		com.alpha.login.SignUp.cityBox.addItem("Zhengzhou");
		com.alpha.login.SignUp.cityBox.addItem("Changsha");
		com.alpha.login.SignUp.cityBox.addItem("Kunming");
		com.alpha.login.SignUp.cityBox.addItem("Changchun");
		com.alpha.login.SignUp.cityBox.addItem("Ürümqi");
		com.alpha.login.SignUp.cityBox.addItem("Shantou†");
		com.alpha.login.SignUp.cityBox.addItem("Hefei");
		com.alpha.login.SignUp.cityBox.addItem("Shijiazhuang");
		com.alpha.login.SignUp.cityBox.addItem("Ningbo");
		com.alpha.login.SignUp.cityBox.addItem("Taiyuan");
		com.alpha.login.SignUp.cityBox.addItem("Nanning");
		com.alpha.login.SignUp.cityBox.addItem("Xiamen");
		com.alpha.login.SignUp.cityBox.addItem("Fuzhou");
		com.alpha.login.SignUp.cityBox.addItem("Wenzho");
		com.alpha.login.SignUp.cityBox.addItem("Changzhou");
		com.alpha.login.SignUp.cityBox.addItem("Nanchang");
		com.alpha.login.SignUp.cityBox.addItem("Tangshan");
		com.alpha.login.SignUp.cityBox.addItem("Guiyang");
		com.alpha.login.SignUp.cityBox.addItem("Wuxi");
		com.alpha.login.SignUp.cityBox.addItem("Lanzhou");
		com.alpha.login.SignUp.cityBox.addItem("Zhongshan");
		com.alpha.login.SignUp.cityBox.addItem("Handan	Hebei");
		com.alpha.login.SignUp.cityBox.addItem("Weifang	Shandong");
		com.alpha.login.SignUp.cityBox.addItem("Huai'an	Jiangsu");
		com.alpha.login.SignUp.cityBox.addItem("Zibo Shandong");
		com.alpha.login.SignUp.cityBox.addItem("Shaoxin Zhejiang");
		com.alpha.login.SignUp.cityBox.addItem("Yantai~	Shandong");
		com.alpha.login.SignUp.cityBox.addItem("Huizhou	Guangdong");
		com.alpha.login.SignUp.cityBox.addItem("Luoyang	Henan");
		com.alpha.login.SignUp.cityBox.addItem("Nantong~");
		com.alpha.login.SignUp.cityBox.addItem("Baotou	Inner Mongolia");
		com.alpha.login.SignUp.cityBox.addItem("Liuzhou	Guangxi");
		
	}
	@SuppressWarnings("unchecked")
	public static void city_Thiland() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Bangkok");
		com.alpha.login.SignUp.cityBox.addItem("Samut Prakan");
		com.alpha.login.SignUp.cityBox.addItem("Mueang Nonthaburi");
		com.alpha.login.SignUp.cityBox.addItem("Udon Thani");
		com.alpha.login.SignUp.cityBox.addItem("Chon Buri");
		com.alpha.login.SignUp.cityBox.addItem("Nakhon Ratchasima");
		com.alpha.login.SignUp.cityBox.addItem("Chiang Mai");
		com.alpha.login.SignUp.cityBox.addItem("Hat Yai");
		com.alpha.login.SignUp.cityBox.addItem("Pak Kret");
		com.alpha.login.SignUp.cityBox.addItem("Si Racha");
		com.alpha.login.SignUp.cityBox.addItem("Phra Pradaeng");
		com.alpha.login.SignUp.cityBox.addItem("Lampang");
		com.alpha.login.SignUp.cityBox.addItem("Khon Kaen");
		com.alpha.login.SignUp.cityBox.addItem("Surat Thani");
		com.alpha.login.SignUp.cityBox.addItem("Ubon Ratchathani");
		com.alpha.login.SignUp.cityBox.addItem("Nakhon Si Thammarat");
		com.alpha.login.SignUp.cityBox.addItem("Khlong Luang");
		com.alpha.login.SignUp.cityBox.addItem("Nakhon Pathom");
		com.alpha.login.SignUp.cityBox.addItem("Rayong");
		com.alpha.login.SignUp.cityBox.addItem("Phitsanulok");
		com.alpha.login.SignUp.cityBox.addItem("Chanthaburi");
		com.alpha.login.SignUp.cityBox.addItem("Pattaya");
		com.alpha.login.SignUp.cityBox.addItem("Yala");
		com.alpha.login.SignUp.cityBox.addItem("Ratchaburi");
		com.alpha.login.SignUp.cityBox.addItem("Nakhon Sawan");
		com.alpha.login.SignUp.cityBox.addItem("Phuket");
		com.alpha.login.SignUp.cityBox.addItem("Ban Mai");
		com.alpha.login.SignUp.cityBox.addItem("Songkhla");
		com.alpha.login.SignUp.cityBox.addItem("Phra Nakhon Si Ayutthaya");
		com.alpha.login.SignUp.cityBox.addItem("Chiang Rai");
		com.alpha.login.SignUp.cityBox.addItem("Bang Kruai");
		com.alpha.login.SignUp.cityBox.addItem("Sakon Nakhon");
		com.alpha.login.SignUp.cityBox.addItem("Krathum Baen");
		com.alpha.login.SignUp.cityBox.addItem("Saraburi");
		com.alpha.login.SignUp.cityBox.addItem("Trang");
		com.alpha.login.SignUp.cityBox.addItem("Sattahip");
		com.alpha.login.SignUp.cityBox.addItem("Kanchanaburi");
		com.alpha.login.SignUp.cityBox.addItem("Nong Khai");
		com.alpha.login.SignUp.cityBox.addItem("Samut Sakhon");
		com.alpha.login.SignUp.cityBox.addItem("Ban Lam Luk Ka");
		com.alpha.login.SignUp.cityBox.addItem("Kamphaeng Phet");
		com.alpha.login.SignUp.cityBox.addItem("Chaiyaphum");
		com.alpha.login.SignUp.cityBox.addItem("Uttaradit");
		com.alpha.login.SignUp.cityBox.addItem("Lop Buri");
		com.alpha.login.SignUp.cityBox.addItem("Ban Pong");
		com.alpha.login.SignUp.cityBox.addItem("Phra Phutthabat");
		com.alpha.login.SignUp.cityBox.addItem("Chumphon");
		com.alpha.login.SignUp.cityBox.addItem("Klaeng");
		com.alpha.login.SignUp.cityBox.addItem("Kalasin");
		com.alpha.login.SignUp.cityBox.addItem("Suphan Buri");
		com.alpha.login.SignUp.cityBox.addItem("Tha Maka");
		com.alpha.login.SignUp.cityBox.addItem("Ban Talat Yai");
		com.alpha.login.SignUp.cityBox.addItem("Maha Sarakham");
		com.alpha.login.SignUp.cityBox.addItem("Phetchabun");
		com.alpha.login.SignUp.cityBox.addItem("Hua Hin");
		com.alpha.login.SignUp.cityBox.addItem("Ko Samui");
		com.alpha.login.SignUp.cityBox.addItem("Chachoengsao");
		com.alpha.login.SignUp.cityBox.addItem("Cha-am");
		com.alpha.login.SignUp.cityBox.addItem("Pak Chong");
		com.alpha.login.SignUp.cityBox.addItem("Narathiwat");
		com.alpha.login.SignUp.cityBox.addItem("Pran Buri");
		com.alpha.login.SignUp.cityBox.addItem("Surin");
		com.alpha.login.SignUp.cityBox.addItem("Phetchaburi");
		com.alpha.login.SignUp.cityBox.addItem("Chum Phae");
		com.alpha.login.SignUp.cityBox.addItem("Sadao");
		com.alpha.login.SignUp.cityBox.addItem("Si Sa Ket");
		com.alpha.login.SignUp.cityBox.addItem("Pattani");
		com.alpha.login.SignUp.cityBox.addItem("Phatthalung");
		com.alpha.login.SignUp.cityBox.addItem("Lamphun");
		com.alpha.login.SignUp.cityBox.addItem("Warin Chamrap");
		com.alpha.login.SignUp.cityBox.addItem("Su-ngai Kolok");
		com.alpha.login.SignUp.cityBox.addItem("Tha Yang");
		com.alpha.login.SignUp.cityBox.addItem("Ban Phaeo");
		com.alpha.login.SignUp.cityBox.addItem("Bang Bua Thong");
		com.alpha.login.SignUp.cityBox.addItem("Nong Khae");
		com.alpha.login.SignUp.cityBox.addItem("Mukdahan");
	}
}