package com.alpha.city;

//in this class there are 5 cities : Bangladesh,India,Pakistan,USA,Qatar;
public class Cities_1 {

	@SuppressWarnings("unchecked")
	public static void city_Bangladesh() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abhaynagar");
		com.alpha.login.SignUp.cityBox.addItem("Bajitpur");
		com.alpha.login.SignUp.cityBox.addItem("Bandarban");
		com.alpha.login.SignUp.cityBox.addItem("Baniachang");
		com.alpha.login.SignUp.cityBox.addItem("Barisal");
		com.alpha.login.SignUp.cityBox.addItem("Bera");
		com.alpha.login.SignUp.cityBox.addItem("Bhairab Bazar");
		com.alpha.login.SignUp.cityBox.addItem("Bhandaria");
		com.alpha.login.SignUp.cityBox.addItem("Bhatpara ");
		com.alpha.login.SignUp.cityBox.addItem("Badarganj");
		com.alpha.login.SignUp.cityBox.addItem("Bheramara");
		com.alpha.login.SignUp.cityBox.addItem("Bhola");
		com.alpha.login.SignUp.cityBox.addItem("Bogra");
		com.alpha.login.SignUp.cityBox.addItem("Burhanuddin");
		com.alpha.login.SignUp.cityBox.addItem("Char Bhadrasan");
		com.alpha.login.SignUp.cityBox.addItem("Chhagalnaiya");
		com.alpha.login.SignUp.cityBox.addItem("Chhatak");
		com.alpha.login.SignUp.cityBox.addItem("Chilmari");
		com.alpha.login.SignUp.cityBox.addItem("Chittagong");
		com.alpha.login.SignUp.cityBox.addItem("Comilla");
		com.alpha.login.SignUp.cityBox.addItem("Cox's Bazar");
		com.alpha.login.SignUp.cityBox.addItem("Dhaka");
		com.alpha.login.SignUp.cityBox.addItem("Dinajpur");
		com.alpha.login.SignUp.cityBox.addItem("Dohar");
		com.alpha.login.SignUp.cityBox.addItem("Faridpur");
		com.alpha.login.SignUp.cityBox.addItem("Fatikchari");
		com.alpha.login.SignUp.cityBox.addItem("Feni");
		com.alpha.login.SignUp.cityBox.addItem("Gafargaon");
		com.alpha.login.SignUp.cityBox.addItem("Gaurnadi");
		com.alpha.login.SignUp.cityBox.addItem("Habiganj");
		com.alpha.login.SignUp.cityBox.addItem("Hajiganj");
		com.alpha.login.SignUp.cityBox.addItem("Ishurdi");
		com.alpha.login.SignUp.cityBox.addItem("Jamalpur");
		com.alpha.login.SignUp.cityBox.addItem("Jessore");
		com.alpha.login.SignUp.cityBox.addItem("Jhingergacha");
		com.alpha.login.SignUp.cityBox.addItem("Joypur Hat");
		com.alpha.login.SignUp.cityBox.addItem("Kalia");
		com.alpha.login.SignUp.cityBox.addItem("Kaliganj");
		com.alpha.login.SignUp.cityBox.addItem("Kesabpur");
		com.alpha.login.SignUp.cityBox.addItem("Khagrachhari");
		com.alpha.login.SignUp.cityBox.addItem("Khulna");
		com.alpha.login.SignUp.cityBox.addItem("Kishorganj");
		com.alpha.login.SignUp.cityBox.addItem("Kushtia");
		com.alpha.login.SignUp.cityBox.addItem("Laksham");
		com.alpha.login.SignUp.cityBox.addItem("Luxmipur");
		com.alpha.login.SignUp.cityBox.addItem("Lalmanirhat");
		com.alpha.login.SignUp.cityBox.addItem("Lalmohan");
		com.alpha.login.SignUp.cityBox.addItem("Madaripur");
		com.alpha.login.SignUp.cityBox.addItem("Manikchari");
		com.alpha.login.SignUp.cityBox.addItem("Mathba");
		com.alpha.login.SignUp.cityBox.addItem("Maulavi Bazar");
		com.alpha.login.SignUp.cityBox.addItem("Mehendiganj");
		com.alpha.login.SignUp.cityBox.addItem("Mirzapur");
		com.alpha.login.SignUp.cityBox.addItem("Morrelgonj");
		com.alpha.login.SignUp.cityBox.addItem("Muktagacha");
		com.alpha.login.SignUp.cityBox.addItem("Mymensingh");
		com.alpha.login.SignUp.cityBox.addItem("Nabinagar");
		com.alpha.login.SignUp.cityBox.addItem("Nagarpur");
		com.alpha.login.SignUp.cityBox.addItem("Nageswari");
		com.alpha.login.SignUp.cityBox.addItem("Nalchiti");
		com.alpha.login.SignUp.cityBox.addItem("Narail");
		com.alpha.login.SignUp.cityBox.addItem("Narayanganj");
		com.alpha.login.SignUp.cityBox.addItem("Narsingdi");
		com.alpha.login.SignUp.cityBox.addItem("Nawabganj");
		com.alpha.login.SignUp.cityBox.addItem("Netrakona");
		com.alpha.login.SignUp.cityBox.addItem("Pabna");
		com.alpha.login.SignUp.cityBox.addItem("Palang");
		com.alpha.login.SignUp.cityBox.addItem("Panchagarh");
		com.alpha.login.SignUp.cityBox.addItem("Par Naogaon");
		com.alpha.login.SignUp.cityBox.addItem("Parbatipur");
		com.alpha.login.SignUp.cityBox.addItem("Patiya");
		com.alpha.login.SignUp.cityBox.addItem("Phultala");
		com.alpha.login.SignUp.cityBox.addItem("Pirgaaj");
		com.alpha.login.SignUp.cityBox.addItem("Pirojpur");
		com.alpha.login.SignUp.cityBox.addItem("Raipur");
		com.alpha.login.SignUp.cityBox.addItem("Rajshahi");
		com.alpha.login.SignUp.cityBox.addItem("Ramganj");
		com.alpha.login.SignUp.cityBox.addItem("Rangpur");
		com.alpha.login.SignUp.cityBox.addItem("Raojan");
		com.alpha.login.SignUp.cityBox.addItem("Savar");
		com.alpha.login.SignUp.cityBox.addItem("Saidpur");
		com.alpha.login.SignUp.cityBox.addItem("Sakhipur");
		com.alpha.login.SignUp.cityBox.addItem("Sandwip");
		com.alpha.login.SignUp.cityBox.addItem("Sarankhola");
		com.alpha.login.SignUp.cityBox.addItem("Sarishabari");
		com.alpha.login.SignUp.cityBox.addItem("Satkania");
		com.alpha.login.SignUp.cityBox.addItem("Satkhira");
		com.alpha.login.SignUp.cityBox.addItem("Shahzadpur");
		com.alpha.login.SignUp.cityBox.addItem("Sherpur");
		com.alpha.login.SignUp.cityBox.addItem("Shibganj");
		com.alpha.login.SignUp.cityBox.addItem("Sirajganj");
		com.alpha.login.SignUp.cityBox.addItem("Sylhet");
		com.alpha.login.SignUp.cityBox.addItem("Tangail");
		com.alpha.login.SignUp.cityBox.addItem("Teknaf");
		com.alpha.login.SignUp.cityBox.addItem("Thakurgaon");
		com.alpha.login.SignUp.cityBox.addItem("Tungi");
		com.alpha.login.SignUp.cityBox.addItem("Tungipara");
		com.alpha.login.SignUp.cityBox.addItem("Uttar Char Fasson");
		com.alpha.login.SignUp.cityBox.addItem("Vola");

	}

	@SuppressWarnings("unchecked")
	public static void city_India() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Agra");
		com.alpha.login.SignUp.cityBox.addItem("Amritsar");
		com.alpha.login.SignUp.cityBox.addItem("Allahabad");
		com.alpha.login.SignUp.cityBox.addItem("Ahmedabad");
		com.alpha.login.SignUp.cityBox.addItem("Aurangabad");
		com.alpha.login.SignUp.cityBox.addItem("Bhopal");
		com.alpha.login.SignUp.cityBox.addItem("Bangalore");
		com.alpha.login.SignUp.cityBox.addItem("Bhubaneswar");
		com.alpha.login.SignUp.cityBox.addItem("Chennai");
		com.alpha.login.SignUp.cityBox.addItem("Coimbatore");
		com.alpha.login.SignUp.cityBox.addItem("Chandigarh");
		com.alpha.login.SignUp.cityBox.addItem("Delhi");
		com.alpha.login.SignUp.cityBox.addItem("Dehradun");
		com.alpha.login.SignUp.cityBox.addItem("Faridabad");
		com.alpha.login.SignUp.cityBox.addItem("Goa");
		com.alpha.login.SignUp.cityBox.addItem("Guwahati");
		com.alpha.login.SignUp.cityBox.addItem("Ghaziabad");
		com.alpha.login.SignUp.cityBox.addItem("Howrah");
		com.alpha.login.SignUp.cityBox.addItem("Haridwar");
		com.alpha.login.SignUp.cityBox.addItem("Hyderabad");
		com.alpha.login.SignUp.cityBox.addItem("Indore");
		com.alpha.login.SignUp.cityBox.addItem("Jaipur");
		com.alpha.login.SignUp.cityBox.addItem("Jammu");
		com.alpha.login.SignUp.cityBox.addItem("Kolkata");
		com.alpha.login.SignUp.cityBox.addItem("Kanpur");
		com.alpha.login.SignUp.cityBox.addItem("Lucknow");
		com.alpha.login.SignUp.cityBox.addItem("Ludhiana");
		com.alpha.login.SignUp.cityBox.addItem("Mumbai");
		com.alpha.login.SignUp.cityBox.addItem("Meerut");
		com.alpha.login.SignUp.cityBox.addItem("Noida");
		com.alpha.login.SignUp.cityBox.addItem("Nagpur");
		com.alpha.login.SignUp.cityBox.addItem("Nashik");
		com.alpha.login.SignUp.cityBox.addItem("Navi Mumbai");
		com.alpha.login.SignUp.cityBox.addItem("Pune");
		com.alpha.login.SignUp.cityBox.addItem("Patna");
		com.alpha.login.SignUp.cityBox.addItem("Pimpri-Chinchwad");
		com.alpha.login.SignUp.cityBox.addItem("Rajkot");
		com.alpha.login.SignUp.cityBox.addItem("Raipur");
		com.alpha.login.SignUp.cityBox.addItem("Ranchi");
		com.alpha.login.SignUp.cityBox.addItem("Surat");
		com.alpha.login.SignUp.cityBox.addItem("Shimla");
		com.alpha.login.SignUp.cityBox.addItem("Solapur");
		com.alpha.login.SignUp.cityBox.addItem("Srinagar");
		com.alpha.login.SignUp.cityBox.addItem("Siliguri");
		com.alpha.login.SignUp.cityBox.addItem("Thane");
		com.alpha.login.SignUp.cityBox.addItem("Visakhapatnam");
		com.alpha.login.SignUp.cityBox.addItem("Vadodara");

	}

	@SuppressWarnings("unchecked")
	public static void city_Pakistan() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abbotabad");
		com.alpha.login.SignUp.cityBox.addItem("Bhalwal");
		com.alpha.login.SignUp.cityBox.addItem("Bahawalpur");
		com.alpha.login.SignUp.cityBox.addItem("Chakwal");
		com.alpha.login.SignUp.cityBox.addItem("Charsadda");
		com.alpha.login.SignUp.cityBox.addItem("Daharki");
		com.alpha.login.SignUp.cityBox.addItem("Dera Ghazi Khan");
		com.alpha.login.SignUp.cityBox.addItem("Dera Ismail Khan");
		com.alpha.login.SignUp.cityBox.addItem("Faisalabad");
		com.alpha.login.SignUp.cityBox.addItem("Gojra");
		com.alpha.login.SignUp.cityBox.addItem("Gujrat");
		com.alpha.login.SignUp.cityBox.addItem("Gujranwala");
		com.alpha.login.SignUp.cityBox.addItem("Hafizabad");
		com.alpha.login.SignUp.cityBox.addItem("Hyderabad");
		com.alpha.login.SignUp.cityBox.addItem("Islamabad");
		com.alpha.login.SignUp.cityBox.addItem("Kohat");
		com.alpha.login.SignUp.cityBox.addItem("Karachi");
		com.alpha.login.SignUp.cityBox.addItem("Khuzdar");
		com.alpha.login.SignUp.cityBox.addItem("Khanewal");
		com.alpha.login.SignUp.cityBox.addItem("Lahore");
		com.alpha.login.SignUp.cityBox.addItem("Larkana");
		com.alpha.login.SignUp.cityBox.addItem("Mirpur");
		com.alpha.login.SignUp.cityBox.addItem("Multan");
		com.alpha.login.SignUp.cityBox.addItem("Mardan");
		com.alpha.login.SignUp.cityBox.addItem("Muzaffarabad");
		com.alpha.login.SignUp.cityBox.addItem("Mirpur Khas");
		com.alpha.login.SignUp.cityBox.addItem("Mirpur Mathelo");
		com.alpha.login.SignUp.cityBox.addItem("Mandi Bahauddin");
		com.alpha.login.SignUp.cityBox.addItem("Narowal");
		com.alpha.login.SignUp.cityBox.addItem("Nawabshah");
		com.alpha.login.SignUp.cityBox.addItem("Peshawar");
		com.alpha.login.SignUp.cityBox.addItem("Quetta");
		com.alpha.login.SignUp.cityBox.addItem("Rawalpindi");
		com.alpha.login.SignUp.cityBox.addItem("Sukkur");
		com.alpha.login.SignUp.cityBox.addItem("Sialkot");
		com.alpha.login.SignUp.cityBox.addItem("Sahiwal");
		com.alpha.login.SignUp.cityBox.addItem("Sargodha");
		com.alpha.login.SignUp.cityBox.addItem("Shahdadkot");
		com.alpha.login.SignUp.cityBox.addItem("Turbat");
		com.alpha.login.SignUp.cityBox.addItem("Vehari");

	}

	@SuppressWarnings("unchecked")
	public static void city_USA() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Alabama");
		com.alpha.login.SignUp.cityBox.addItem("Alaska");
		com.alpha.login.SignUp.cityBox.addItem("Arizona");
		com.alpha.login.SignUp.cityBox.addItem("Arkansas");
		com.alpha.login.SignUp.cityBox.addItem("California");
		com.alpha.login.SignUp.cityBox.addItem("Colorado");
		com.alpha.login.SignUp.cityBox.addItem("Connecticut");
		com.alpha.login.SignUp.cityBox.addItem("Delaware");
		com.alpha.login.SignUp.cityBox.addItem("Florida");
		com.alpha.login.SignUp.cityBox.addItem("Georgia");
		com.alpha.login.SignUp.cityBox.addItem("Hawaii");
		com.alpha.login.SignUp.cityBox.addItem("Idaho");
		com.alpha.login.SignUp.cityBox.addItem("Illinois");
		com.alpha.login.SignUp.cityBox.addItem("Indiana");
		com.alpha.login.SignUp.cityBox.addItem("Iowa");
		com.alpha.login.SignUp.cityBox.addItem("Kansas");
		com.alpha.login.SignUp.cityBox.addItem("Kentucky");
		com.alpha.login.SignUp.cityBox.addItem("Louisiana");
		com.alpha.login.SignUp.cityBox.addItem("Maine");
		com.alpha.login.SignUp.cityBox.addItem("Maryland");
		com.alpha.login.SignUp.cityBox.addItem("Massachusetts");
		com.alpha.login.SignUp.cityBox.addItem("Michigan");
		com.alpha.login.SignUp.cityBox.addItem("Minnesota");
		com.alpha.login.SignUp.cityBox.addItem("Mississippi");
		com.alpha.login.SignUp.cityBox.addItem("Missouri");
		com.alpha.login.SignUp.cityBox.addItem("Montana");
		com.alpha.login.SignUp.cityBox.addItem("Nebraska");
		com.alpha.login.SignUp.cityBox.addItem("Nevada");
		com.alpha.login.SignUp.cityBox.addItem("New Hampshire");
		com.alpha.login.SignUp.cityBox.addItem("New Jersey");
		com.alpha.login.SignUp.cityBox.addItem("New Mexico");
		com.alpha.login.SignUp.cityBox.addItem("New York");
		com.alpha.login.SignUp.cityBox.addItem("North Carolina");
		com.alpha.login.SignUp.cityBox.addItem("North Dakota");
		com.alpha.login.SignUp.cityBox.addItem("Ohio");
		com.alpha.login.SignUp.cityBox.addItem("Oklahoma");
		com.alpha.login.SignUp.cityBox.addItem("Oregon");
		com.alpha.login.SignUp.cityBox.addItem("Pennsylvania");
		com.alpha.login.SignUp.cityBox.addItem("Rhode Island");
		com.alpha.login.SignUp.cityBox.addItem("South Carolina");
		com.alpha.login.SignUp.cityBox.addItem("South Dakota");
		com.alpha.login.SignUp.cityBox.addItem("Tennessee");
		com.alpha.login.SignUp.cityBox.addItem("Texas");
		com.alpha.login.SignUp.cityBox.addItem("Utah");
		com.alpha.login.SignUp.cityBox.addItem("Vermont");
		com.alpha.login.SignUp.cityBox.addItem("Virginia");
		com.alpha.login.SignUp.cityBox.addItem("Washington");
		com.alpha.login.SignUp.cityBox.addItem("West Virginia");
		com.alpha.login.SignUp.cityBox.addItem("Wisconsin");
		com.alpha.login.SignUp.cityBox.addItem("Wyoming");
	}
	@SuppressWarnings("unchecked")
	public static void city_Germany() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Berlin");
		com.alpha.login.SignUp.cityBox.addItem("Hamburg");
		com.alpha.login.SignUp.cityBox.addItem("Munich");
		com.alpha.login.SignUp.cityBox.addItem("Cologne");
		com.alpha.login.SignUp.cityBox.addItem("Frankfurt");
		com.alpha.login.SignUp.cityBox.addItem("Stuttgart");
		com.alpha.login.SignUp.cityBox.addItem("Düsseldorf");
		com.alpha.login.SignUp.cityBox.addItem("Dortmund");
		com.alpha.login.SignUp.cityBox.addItem("Essen");
		com.alpha.login.SignUp.cityBox.addItem("Leipzig");
		com.alpha.login.SignUp.cityBox.addItem("Bremen");
		com.alpha.login.SignUp.cityBox.addItem("Dresden");
		com.alpha.login.SignUp.cityBox.addItem("Hanover");
		com.alpha.login.SignUp.cityBox.addItem("Nuremberg");
		com.alpha.login.SignUp.cityBox.addItem("Duisburg");
		com.alpha.login.SignUp.cityBox.addItem("Bochum");
		com.alpha.login.SignUp.cityBox.addItem("Wuppertal");
		com.alpha.login.SignUp.cityBox.addItem("Bielefeld");
		com.alpha.login.SignUp.cityBox.addItem("Bonn");
		com.alpha.login.SignUp.cityBox.addItem("Münster");
		com.alpha.login.SignUp.cityBox.addItem("Karlsruhe");
		com.alpha.login.SignUp.cityBox.addItem("Mannheim");
		com.alpha.login.SignUp.cityBox.addItem("Augsburg");
		com.alpha.login.SignUp.cityBox.addItem("Wiesbaden");
		com.alpha.login.SignUp.cityBox.addItem("Gelsenkirchen");
		com.alpha.login.SignUp.cityBox.addItem("Mönchengladbach");
		com.alpha.login.SignUp.cityBox.addItem("Braunschweig");
		com.alpha.login.SignUp.cityBox.addItem("Chemnitz");
		com.alpha.login.SignUp.cityBox.addItem("Kiel");
		com.alpha.login.SignUp.cityBox.addItem("Aachen");
		com.alpha.login.SignUp.cityBox.addItem("North Rhine-Westphalia");
		com.alpha.login.SignUp.cityBox.addItem("Halle");
		com.alpha.login.SignUp.cityBox.addItem("Magdeburg");
		com.alpha.login.SignUp.cityBox.addItem("Freiburg im Breisgau");
		com.alpha.login.SignUp.cityBox.addItem("Krefeld");
		com.alpha.login.SignUp.cityBox.addItem("Lübeck");
		com.alpha.login.SignUp.cityBox.addItem("Oberhausen");
		com.alpha.login.SignUp.cityBox.addItem("Erfurt");
		com.alpha.login.SignUp.cityBox.addItem("Mainz");
		
	}
}