package com.alpha.city;

public class Cities_5 {
	@SuppressWarnings("unchecked")
	public static void city_Malasiya() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Kuala Lumpur");
		com.alpha.login.SignUp.cityBox.addItem("Ipoh");
		com.alpha.login.SignUp.cityBox.addItem("Kuching");
		com.alpha.login.SignUp.cityBox.addItem("Johor Bahru");
		com.alpha.login.SignUp.cityBox.addItem("Kota Kinabalu");
		com.alpha.login.SignUp.cityBox.addItem("Shah Alam");
		com.alpha.login.SignUp.cityBox.addItem("Malacca City");
		com.alpha.login.SignUp.cityBox.addItem("Alor Setar");
		com.alpha.login.SignUp.cityBox.addItem("Miri");
		com.alpha.login.SignUp.cityBox.addItem("Petaling Jaya");
		com.alpha.login.SignUp.cityBox.addItem("Kuala Terengganu");
		com.alpha.login.SignUp.cityBox.addItem("Iskandar Puteri");
		com.alpha.login.SignUp.cityBox.addItem("Seberang Perai");
		com.alpha.login.SignUp.cityBox.addItem("Seremban");
		com.alpha.login.SignUp.cityBox.addItem("Subang Jaya");
		com.alpha.login.SignUp.cityBox.addItem("Pasir Gudang");
		com.alpha.login.SignUp.cityBox.addItem("Kuantan");
	}
	@SuppressWarnings("unchecked")
	public static void city_Maldives() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Addu City");
		com.alpha.login.SignUp.cityBox.addItem("Dhidhdhoo");
		com.alpha.login.SignUp.cityBox.addItem("Kulhudhuffushi");
		com.alpha.login.SignUp.cityBox.addItem("Eydhafushi");
		com.alpha.login.SignUp.cityBox.addItem("Farukolhufunadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Felidhoo");
		com.alpha.login.SignUp.cityBox.addItem("Funadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Gan");
		com.alpha.login.SignUp.cityBox.addItem("Hinnavaru");
		com.alpha.login.SignUp.cityBox.addItem("Hithadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Hulhumalé");
		com.alpha.login.SignUp.cityBox.addItem("Hulhumeedhoo");
		com.alpha.login.SignUp.cityBox.addItem("Kudahuvadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Magoodhoo");
		com.alpha.login.SignUp.cityBox.addItem("Mahibadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Manadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Maroshi");
		com.alpha.login.SignUp.cityBox.addItem("Meedhoo");
		com.alpha.login.SignUp.cityBox.addItem("Mula");
		com.alpha.login.SignUp.cityBox.addItem("Naifaru");
		com.alpha.login.SignUp.cityBox.addItem("Nolhivaranfaru");
		com.alpha.login.SignUp.cityBox.addItem("Thinadhoo");
		com.alpha.login.SignUp.cityBox.addItem("Ungoofaaru");
		com.alpha.login.SignUp.cityBox.addItem("Veymandhoo");
		com.alpha.login.SignUp.cityBox.addItem("Veymandoo");
		com.alpha.login.SignUp.cityBox.addItem("Viligili");
		com.alpha.login.SignUp.cityBox.addItem("Villingili");
		
		
	}
	@SuppressWarnings("unchecked")
	public static void city_Turkey() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Adana‎");
		com.alpha.login.SignUp.cityBox.addItem("Adıyaman‎");
		com.alpha.login.SignUp.cityBox.addItem("Afyonkarahisar‎");
		com.alpha.login.SignUp.cityBox.addItem("Aksaray‎");
		com.alpha.login.SignUp.cityBox.addItem("Alanya‎");
		com.alpha.login.SignUp.cityBox.addItem("Amasya‎");
		com.alpha.login.SignUp.cityBox.addItem("Anamur‎");
		com.alpha.login.SignUp.cityBox.addItem("Ankara‎");
		com.alpha.login.SignUp.cityBox.addItem("Antakya");
		com.alpha.login.SignUp.cityBox.addItem("Antalya‎");
		com.alpha.login.SignUp.cityBox.addItem("Ardahan‎");
		com.alpha.login.SignUp.cityBox.addItem("Artvin");
		com.alpha.login.SignUp.cityBox.addItem("Aydın");
		com.alpha.login.SignUp.cityBox.addItem("Ayvalık");
		com.alpha.login.SignUp.cityBox.addItem("Balıkesir‎");
		com.alpha.login.SignUp.cityBox.addItem("Bartın");
		com.alpha.login.SignUp.cityBox.addItem("Bitlis‎");
		com.alpha.login.SignUp.cityBox.addItem("Bodrum‎");
		com.alpha.login.SignUp.cityBox.addItem("Bolu‎");
		com.alpha.login.SignUp.cityBox.addItem("Burdur‎");
		com.alpha.login.SignUp.cityBox.addItem("Bursa‎");
		com.alpha.login.SignUp.cityBox.addItem("Canakkale‎");
		com.alpha.login.SignUp.cityBox.addItem("Cankırı‎");
		com.alpha.login.SignUp.cityBox.addItem("Corum‎");
		com.alpha.login.SignUp.cityBox.addItem("Denizli‎");
		com.alpha.login.SignUp.cityBox.addItem("Diyarbakır‎");
		com.alpha.login.SignUp.cityBox.addItem("Duzce‎");
		com.alpha.login.SignUp.cityBox.addItem("Edirne‎");
		com.alpha.login.SignUp.cityBox.addItem("Erbaa‎");
		com.alpha.login.SignUp.cityBox.addItem("Erzincan‎");
		com.alpha.login.SignUp.cityBox.addItem("Erzurum‎");
		com.alpha.login.SignUp.cityBox.addItem("Fethiye‎");
		com.alpha.login.SignUp.cityBox.addItem("Gaziantep‎");
		com.alpha.login.SignUp.cityBox.addItem("Gebze‎");
		com.alpha.login.SignUp.cityBox.addItem("Gelibolu‎");
		com.alpha.login.SignUp.cityBox.addItem("Giresun‎");
		com.alpha.login.SignUp.cityBox.addItem("Hakkari‎");
		com.alpha.login.SignUp.cityBox.addItem("Igdır‎");
		com.alpha.login.SignUp.cityBox.addItem("Iskenderun‎");
		com.alpha.login.SignUp.cityBox.addItem("Isparta‎");
		com.alpha.login.SignUp.cityBox.addItem("Istanbul‎");
		com.alpha.login.SignUp.cityBox.addItem("Izmir‎");
		com.alpha.login.SignUp.cityBox.addItem("Kandıra‎");
		com.alpha.login.SignUp.cityBox.addItem("Karaman‎");
		com.alpha.login.SignUp.cityBox.addItem("Kars‎");
		com.alpha.login.SignUp.cityBox.addItem("Kastamonu‎");
		com.alpha.login.SignUp.cityBox.addItem("Kayseri‎");
		com.alpha.login.SignUp.cityBox.addItem("Kilis‎");
		com.alpha.login.SignUp.cityBox.addItem("Kırklareli‎");
		com.alpha.login.SignUp.cityBox.addItem("Kırıkkale‎");
		com.alpha.login.SignUp.cityBox.addItem("Konya‎");
		com.alpha.login.SignUp.cityBox.addItem("Malatya‎");
		com.alpha.login.SignUp.cityBox.addItem("Manisa‎");
		com.alpha.login.SignUp.cityBox.addItem("Mardin‎");
		com.alpha.login.SignUp.cityBox.addItem("Marmaris‎");
		com.alpha.login.SignUp.cityBox.addItem("Mersin‎");
		com.alpha.login.SignUp.cityBox.addItem("Milas‎");
		com.alpha.login.SignUp.cityBox.addItem("Nazilli‎");
		com.alpha.login.SignUp.cityBox.addItem("Niksar‎");
		com.alpha.login.SignUp.cityBox.addItem("Ordu‎v");
		com.alpha.login.SignUp.cityBox.addItem("Osmaniye‎");
		com.alpha.login.SignUp.cityBox.addItem("Rize‎");
		com.alpha.login.SignUp.cityBox.addItem("Samsun‎");
		com.alpha.login.SignUp.cityBox.addItem("Sinop");
		com.alpha.login.SignUp.cityBox.addItem("Sivas‎");
		com.alpha.login.SignUp.cityBox.addItem("Tokat‎");
		com.alpha.login.SignUp.cityBox.addItem("Trabzon‎");
		com.alpha.login.SignUp.cityBox.addItem("Tunceli‎");
		com.alpha.login.SignUp.cityBox.addItem("Van‎");
		com.alpha.login.SignUp.cityBox.addItem("Yalova‎");
		com.alpha.login.SignUp.cityBox.addItem("Yomra‎");
		com.alpha.login.SignUp.cityBox.addItem("Yozgat‎");
		com.alpha.login.SignUp.cityBox.addItem("Zonguldak‎");
	}
@SuppressWarnings("unchecked")
public static void city_Oman() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Adam");
		com.alpha.login.SignUp.cityBox.addItem("As Sib");
		com.alpha.login.SignUp.cityBox.addItem("Al Ashkharah");
		com.alpha.login.SignUp.cityBox.addItem("Al Buraimi");
		com.alpha.login.SignUp.cityBox.addItem("Al Hamra");
		com.alpha.login.SignUp.cityBox.addItem("Al Jazer");
		com.alpha.login.SignUp.cityBox.addItem("Al Madina A'Zarqa");
		com.alpha.login.SignUp.cityBox.addItem("Al Suwaiq");
		com.alpha.login.SignUp.cityBox.addItem("Bahla");
		com.alpha.login.SignUp.cityBox.addItem("Barka");
		com.alpha.login.SignUp.cityBox.addItem("Bidbid");
		com.alpha.login.SignUp.cityBox.addItem("Bidiya");
		com.alpha.login.SignUp.cityBox.addItem("Duqm");
		com.alpha.login.SignUp.cityBox.addItem("Haima");
		com.alpha.login.SignUp.cityBox.addItem("Ibra");
		com.alpha.login.SignUp.cityBox.addItem("Ibri");
        com.alpha.login.SignUp.cityBox.addItem("Izki");
		com.alpha.login.SignUp.cityBox.addItem("Jabrin");
		com.alpha.login.SignUp.cityBox.addItem("Jalan Bani Bu Hassan");
		com.alpha.login.SignUp.cityBox.addItem("Khasab");
		com.alpha.login.SignUp.cityBox.addItem("Mahooth");
		com.alpha.login.SignUp.cityBox.addItem("Manah");
		com.alpha.login.SignUp.cityBox.addItem("Masirah");
		com.alpha.login.SignUp.cityBox.addItem("Matrah");
		com.alpha.login.SignUp.cityBox.addItem("Mudhaybi");
		com.alpha.login.SignUp.cityBox.addItem("Mudhaireb");
		com.alpha.login.SignUp.cityBox.addItem("Muscat");
		com.alpha.login.SignUp.cityBox.addItem("Nizwa");
		com.alpha.login.SignUp.cityBox.addItem("Quriyat");
		com.alpha.login.SignUp.cityBox.addItem("Raysut");
		com.alpha.login.SignUp.cityBox.addItem("Rustaq");
		com.alpha.login.SignUp.cityBox.addItem("Ruwi");
        com.alpha.login.SignUp.cityBox.addItem("Saham");
		com.alpha.login.SignUp.cityBox.addItem("Shinas");
		com.alpha.login.SignUp.cityBox.addItem("Saiq");
		com.alpha.login.SignUp.cityBox.addItem("Salalah");
		com.alpha.login.SignUp.cityBox.addItem("Samail");
		com.alpha.login.SignUp.cityBox.addItem("Sohar");
		com.alpha.login.SignUp.cityBox.addItem("Sur");
		com.alpha.login.SignUp.cityBox.addItem("Tan`am");
		com.alpha.login.SignUp.cityBox.addItem("Thumrait");
	}
@SuppressWarnings("unchecked")
public static void city_Egypt() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abu El Matamir");
		com.alpha.login.SignUp.cityBox.addItem("Abu Hummus");
		com.alpha.login.SignUp.cityBox.addItem("Abu Tesht");
		com.alpha.login.SignUp.cityBox.addItem("Akhmim");
		com.alpha.login.SignUp.cityBox.addItem("Al Khankah");
		com.alpha.login.SignUp.cityBox.addItem("Alexandria");
		com.alpha.login.SignUp.cityBox.addItem("Arish");
		com.alpha.login.SignUp.cityBox.addItem("Ashmoun");
		com.alpha.login.SignUp.cityBox.addItem("Aswan");
		com.alpha.login.SignUp.cityBox.addItem("Asyut");
		com.alpha.login.SignUp.cityBox.addItem("Awsim");
		com.alpha.login.SignUp.cityBox.addItem("Badr");
		com.alpha.login.SignUp.cityBox.addItem("Baltim");
		com.alpha.login.SignUp.cityBox.addItem("Banha");
		com.alpha.login.SignUp.cityBox.addItem("Basyoun");
		com.alpha.login.SignUp.cityBox.addItem("Biba");
		com.alpha.login.SignUp.cityBox.addItem("Bilbeis");
		com.alpha.login.SignUp.cityBox.addItem("Birket El Sab");
		com.alpha.login.SignUp.cityBox.addItem("Borg El Arab");
		com.alpha.login.SignUp.cityBox.addItem("Borg El Burullus");
		com.alpha.login.SignUp.cityBox.addItem("Bush");
		com.alpha.login.SignUp.cityBox.addItem("Cairo");
		com.alpha.login.SignUp.cityBox.addItem("Dahab");
		com.alpha.login.SignUp.cityBox.addItem("Dairut");
		com.alpha.login.SignUp.cityBox.addItem("Damanhur");
		com.alpha.login.SignUp.cityBox.addItem("Damietta");
		com.alpha.login.SignUp.cityBox.addItem("Dar El Salam");
		com.alpha.login.SignUp.cityBox.addItem("Daraw");
		com.alpha.login.SignUp.cityBox.addItem("Deir Mawas");
		com.alpha.login.SignUp.cityBox.addItem("Dekernes");
		com.alpha.login.SignUp.cityBox.addItem("Dendera");
		com.alpha.login.SignUp.cityBox.addItem("Desouk");
		com.alpha.login.SignUp.cityBox.addItem("Dishna");
		com.alpha.login.SignUp.cityBox.addItem("Edfu");
		com.alpha.login.SignUp.cityBox.addItem("Edku");
		com.alpha.login.SignUp.cityBox.addItem("El Alamein");
		com.alpha.login.SignUp.cityBox.addItem("El Arish");
		com.alpha.login.SignUp.cityBox.addItem("El Ayyat");
		com.alpha.login.SignUp.cityBox.addItem("El Badari");
		com.alpha.login.SignUp.cityBox.addItem("El Badrashein");
		com.alpha.login.SignUp.cityBox.addItem("El Bagour");
		com.alpha.login.SignUp.cityBox.addItem("El Balyana");
		com.alpha.login.SignUp.cityBox.addItem("El Basaliya");
		com.alpha.login.SignUp.cityBox.addItem("El Bayadiya");
		com.alpha.login.SignUp.cityBox.addItem("El Dabaa");
		com.alpha.login.SignUp.cityBox.addItem("El Delengat");
		com.alpha.login.SignUp.cityBox.addItem("El Fashn");
		com.alpha.login.SignUp.cityBox.addItem("El Gamaliya");
		com.alpha.login.SignUp.cityBox.addItem("El Ghanayem");
		com.alpha.login.SignUp.cityBox.addItem("El Hamool");
		com.alpha.login.SignUp.cityBox.addItem("El Hamam");
		com.alpha.login.SignUp.cityBox.addItem("El Hawamdeya");
		com.alpha.login.SignUp.cityBox.addItem("El Husseiniya");
		com.alpha.login.SignUp.cityBox.addItem("El Idwa");
		com.alpha.login.SignUp.cityBox.addItem("El Ibrahimiya");
		com.alpha.login.SignUp.cityBox.addItem("El Kanayat");
		com.alpha.login.SignUp.cityBox.addItem("El Kareen");
		com.alpha.login.SignUp.cityBox.addItem("El Mahmoudiyah");
		com.alpha.login.SignUp.cityBox.addItem("El Mansha");
		com.alpha.login.SignUp.cityBox.addItem("El Manzala");
		com.alpha.login.SignUp.cityBox.addItem("El Maragha");
		com.alpha.login.SignUp.cityBox.addItem("El Matareya");
		com.alpha.login.SignUp.cityBox.addItem("El Qantara");
		com.alpha.login.SignUp.cityBox.addItem("El Qoseir");
		com.alpha.login.SignUp.cityBox.addItem("El Qusiya");
		com.alpha.login.SignUp.cityBox.addItem("El Rahmaniya");
		com.alpha.login.SignUp.cityBox.addItem("El Reyad");
		com.alpha.login.SignUp.cityBox.addItem("El Saff");
		com.alpha.login.SignUp.cityBox.addItem("El Santa");
		com.alpha.login.SignUp.cityBox.addItem("Faqous");
		com.alpha.login.SignUp.cityBox.addItem("Faraskur");
		com.alpha.login.SignUp.cityBox.addItem("Farshut");
		com.alpha.login.SignUp.cityBox.addItem("Fayed");
		com.alpha.login.SignUp.cityBox.addItem("Faiyum");
		com.alpha.login.SignUp.cityBox.addItem("Fuka");
		com.alpha.login.SignUp.cityBox.addItem("Girga");
		com.alpha.login.SignUp.cityBox.addItem("Giza");
		com.alpha.login.SignUp.cityBox.addItem("Hihya");
		com.alpha.login.SignUp.cityBox.addItem("Hosh Essa");
		com.alpha.login.SignUp.cityBox.addItem("Hurghada");
		com.alpha.login.SignUp.cityBox.addItem("Ibsheway");
		com.alpha.login.SignUp.cityBox.addItem("Ihnasiya");
		com.alpha.login.SignUp.cityBox.addItem("Ismailia");
		com.alpha.login.SignUp.cityBox.addItem("Itay El Barud");
		com.alpha.login.SignUp.cityBox.addItem("Itsa");
		com.alpha.login.SignUp.cityBox.addItem("Juhayna");
		com.alpha.login.SignUp.cityBox.addItem("Kafr El Sheikh");
		com.alpha.login.SignUp.cityBox.addItem("Kafr El Zayat");
		com.alpha.login.SignUp.cityBox.addItem("Kafr El Batikh");
		com.alpha.login.SignUp.cityBox.addItem("Kafr El Dawwar");
		com.alpha.login.SignUp.cityBox.addItem("Kafr Saad");
		com.alpha.login.SignUp.cityBox.addItem("Kerdasa");
		com.alpha.login.SignUp.cityBox.addItem("Khanka");
		com.alpha.login.SignUp.cityBox.addItem("Kharga");
		com.alpha.login.SignUp.cityBox.addItem("Khusus");
		com.alpha.login.SignUp.cityBox.addItem("Kom Ombo");
		com.alpha.login.SignUp.cityBox.addItem("Luxor");
		com.alpha.login.SignUp.cityBox.addItem("Maghagha");
		com.alpha.login.SignUp.cityBox.addItem("Mallawi");
		com.alpha.login.SignUp.cityBox.addItem("Manfalut");
		com.alpha.login.SignUp.cityBox.addItem("Mansoura");
		com.alpha.login.SignUp.cityBox.addItem("Matai");
		com.alpha.login.SignUp.cityBox.addItem("Menouf");
		com.alpha.login.SignUp.cityBox.addItem("Marsa Alam");
		com.alpha.login.SignUp.cityBox.addItem("Mersa Matruh");
		com.alpha.login.SignUp.cityBox.addItem("Metoubes");
		com.alpha.login.SignUp.cityBox.addItem("Minya");
		com.alpha.login.SignUp.cityBox.addItem("Minyet El Nasr");
		com.alpha.login.SignUp.cityBox.addItem("Mit Abu El Kom");
		com.alpha.login.SignUp.cityBox.addItem("Mit Adlan");
		com.alpha.login.SignUp.cityBox.addItem("Mit Bera");
		com.alpha.login.SignUp.cityBox.addItem("Mit El Korama");
		com.alpha.login.SignUp.cityBox.addItem("Mit Elwan");
		com.alpha.login.SignUp.cityBox.addItem("Mit Ghamr");
		com.alpha.login.SignUp.cityBox.addItem("Mit Rahina");
		com.alpha.login.SignUp.cityBox.addItem("Mut");
		com.alpha.login.SignUp.cityBox.addItem("Nabaroh");
		com.alpha.login.SignUp.cityBox.addItem("Nag Hammadi");
		com.alpha.login.SignUp.cityBox.addItem("Naqada");
		com.alpha.login.SignUp.cityBox.addItem("New Alamein");
		com.alpha.login.SignUp.cityBox.addItem("New Asyut");
		com.alpha.login.SignUp.cityBox.addItem("New Cairo");
		com.alpha.login.SignUp.cityBox.addItem("New Damietta");
		com.alpha.login.SignUp.cityBox.addItem("New Minya");
		com.alpha.login.SignUp.cityBox.addItem("New Nubariya");
		com.alpha.login.SignUp.cityBox.addItem("Obour");
		com.alpha.login.SignUp.cityBox.addItem("Port Said");
		com.alpha.login.SignUp.cityBox.addItem("Qaha");
		com.alpha.login.SignUp.cityBox.addItem("Qallin");
		com.alpha.login.SignUp.cityBox.addItem("Qalyub");
		com.alpha.login.SignUp.cityBox.addItem("Qena");
		com.alpha.login.SignUp.cityBox.addItem("Qift");
		com.alpha.login.SignUp.cityBox.addItem("Quesna");
		com.alpha.login.SignUp.cityBox.addItem("Qus");
		com.alpha.login.SignUp.cityBox.addItem("Rafah");
		com.alpha.login.SignUp.cityBox.addItem("Ras Burqa");
		com.alpha.login.SignUp.cityBox.addItem("Ras El Bar");
		com.alpha.login.SignUp.cityBox.addItem("Ras Gharib");
		com.alpha.login.SignUp.cityBox.addItem("Ras Sedr");
		com.alpha.login.SignUp.cityBox.addItem("Ras Shokeir");
		com.alpha.login.SignUp.cityBox.addItem("Rosetta");
		com.alpha.login.SignUp.cityBox.addItem("Sadat");
		com.alpha.login.SignUp.cityBox.addItem("Safaga");
		com.alpha.login.SignUp.cityBox.addItem("Sahel Selim");
		com.alpha.login.SignUp.cityBox.addItem("Saint Catherine");
		com.alpha.login.SignUp.cityBox.addItem("Samalut");
		com.alpha.login.SignUp.cityBox.addItem("Samanoud");
		com.alpha.login.SignUp.cityBox.addItem("Saqultah");
		com.alpha.login.SignUp.cityBox.addItem("Shubra Khit");
		com.alpha.login.SignUp.cityBox.addItem("Sharm El Sheikh");
		com.alpha.login.SignUp.cityBox.addItem("Sherbin");
		com.alpha.login.SignUp.cityBox.addItem("Sheikh Zuweid");
		com.alpha.login.SignUp.cityBox.addItem("Shibin El Qanater");
		com.alpha.login.SignUp.cityBox.addItem("Shibin El Kom");
		com.alpha.login.SignUp.cityBox.addItem("Shubra El Kheima");
		com.alpha.login.SignUp.cityBox.addItem("Sidi Barrani");
		com.alpha.login.SignUp.cityBox.addItem("Sidi Salem");
		com.alpha.login.SignUp.cityBox.addItem("Sinnuris");
		com.alpha.login.SignUp.cityBox.addItem("Siwa Oasis");
		com.alpha.login.SignUp.cityBox.addItem("Sodfa");
		com.alpha.login.SignUp.cityBox.addItem("Sohag");
		com.alpha.login.SignUp.cityBox.addItem("Suez");
		com.alpha.login.SignUp.cityBox.addItem("Tahta");
		com.alpha.login.SignUp.cityBox.addItem("Tala");
		com.alpha.login.SignUp.cityBox.addItem("Talkha");
		com.alpha.login.SignUp.cityBox.addItem("Tamiya");
		com.alpha.login.SignUp.cityBox.addItem("Tanta");
		com.alpha.login.SignUp.cityBox.addItem("Tell El Kebir");
		com.alpha.login.SignUp.cityBox.addItem("Tima");
		com.alpha.login.SignUp.cityBox.addItem("Tukh");
		com.alpha.login.SignUp.cityBox.addItem("Wadi El Natrun");
		com.alpha.login.SignUp.cityBox.addItem("Zagazig");
		com.alpha.login.SignUp.cityBox.addItem("Zefta");
	
	}
}