package com.alpha.city;
//in this class there are 5 cities : UAE,Saudi Arabia,Qatar,Sri_Lanka;
public class Cities_2 {
	@SuppressWarnings("unchecked")
	public static void city_Singapore() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Singapore");
		com.alpha.login.SignUp.cityBox.addItem("Keat Hong Village");
		com.alpha.login.SignUp.cityBox.addItem("Choa Chu Kang New Town");
		com.alpha.login.SignUp.cityBox.addItem("Bukit PEstateanjang");
		com.alpha.login.SignUp.cityBox.addItem("Jalan Kayu");
		com.alpha.login.SignUp.cityBox.addItem("Bukit Sembawang Estate");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Serangoon Kechil");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Cutforth");
		com.alpha.login.SignUp.cityBox.addItem("Mok Peng Hiang Estate");
		com.alpha.login.SignUp.cityBox.addItem("Woodlands New Town");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Pinang");
		com.alpha.login.SignUp.cityBox.addItem("Serangoon");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Sungai Tengah");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Tongkang Pechah");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Teban");
		com.alpha.login.SignUp.cityBox.addItem("Kangkar");
		com.alpha.login.SignUp.cityBox.addItem("Jurong Town");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Ulu Jurong");
		com.alpha.login.SignUp.cityBox.addItem("Seletar Hills Estate");
		com.alpha.login.SignUp.cityBox.addItem("Tay Keng Loon Estate");
		com.alpha.login.SignUp.cityBox.addItem("Matilda Estate");
		com.alpha.login.SignUp.cityBox.addItem("Bukit Panjang New Town");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Beremban");
		com.alpha.login.SignUp.cityBox.addItem("Marsiling");
		com.alpha.login.SignUp.cityBox.addItem("Chia Keng");
		com.alpha.login.SignUp.cityBox.addItem("Somapah Serangoon");
		com.alpha.login.SignUp.cityBox.addItem("Jurong West");
		com.alpha.login.SignUp.cityBox.addItem("Boon Lay");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Chai Chee");
		com.alpha.login.SignUp.cityBox.addItem("Ulu Bedok");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Pachitan");
		com.alpha.login.SignUp.cityBox.addItem("Bedok New Town");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Sireh");
		com.alpha.login.SignUp.cityBox.addItem("Bedok Ville");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Bukit Panjang");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Lew Lian");
		com.alpha.login.SignUp.cityBox.addItem("Marsiling Estate");
		com.alpha.login.SignUp.cityBox.addItem("Ang Mo Kio New Town");
		com.alpha.login.SignUp.cityBox.addItem("Kampong Amoy Quee");
	}
	@SuppressWarnings("unchecked")
	public static void city_Saudi_Arabia() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abha");
		com.alpha.login.SignUp.cityBox.addItem("Ad-Dilam");
		com.alpha.login.SignUp.cityBox.addItem("Al-Abwa");
		com.alpha.login.SignUp.cityBox.addItem("Al Artaweeiyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Bukayriyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Bahah");
		com.alpha.login.SignUp.cityBox.addItem("Al-Gwei'iyyah");
		com.alpha.login.SignUp.cityBox.addItem("Al-Hareeq");
		com.alpha.login.SignUp.cityBox.addItem("Al Jafr");
		com.alpha.login.SignUp.cityBox.addItem("Al-Saih");
		com.alpha.login.SignUp.cityBox.addItem("Al-Khutt");
		com.alpha.login.SignUp.cityBox.addItem("Al Lith");
		com.alpha.login.SignUp.cityBox.addItem("Al Majma'ah");
		com.alpha.login.SignUp.cityBox.addItem("Al Mikhwah");
		com.alpha.login.SignUp.cityBox.addItem("Al-Mubarraz");
		com.alpha.login.SignUp.cityBox.addItem("Al Mawain");
		com.alpha.login.SignUp.cityBox.addItem("Al-Namas");
		com.alpha.login.SignUp.cityBox.addItem("Al-Omran");
		com.alpha.login.SignUp.cityBox.addItem("Al-Oyoon");
		com.alpha.login.SignUp.cityBox.addItem("Al Qunfudhah");
		com.alpha.login.SignUp.cityBox.addItem("Ar Rass");
		com.alpha.login.SignUp.cityBox.addItem("Az Zaimah");
		com.alpha.login.SignUp.cityBox.addItem("Badr");
		com.alpha.login.SignUp.cityBox.addItem("Baljurashi");
		com.alpha.login.SignUp.cityBox.addItem("Bisha");
		com.alpha.login.SignUp.cityBox.addItem("Bareq");
		com.alpha.login.SignUp.cityBox.addItem("Buraydah");
		com.alpha.login.SignUp.cityBox.addItem("Dammam");
		com.alpha.login.SignUp.cityBox.addItem("Dhahran");
		com.alpha.login.SignUp.cityBox.addItem("Dhurma");
		com.alpha.login.SignUp.cityBox.addItem("Dahaban");
		com.alpha.login.SignUp.cityBox.addItem("Diriyah");
		com.alpha.login.SignUp.cityBox.addItem("Duba");
		com.alpha.login.SignUp.cityBox.addItem("Dumat Al-Jandal");
		com.alpha.login.SignUp.cityBox.addItem("Dawadmi");
		com.alpha.login.SignUp.cityBox.addItem("Farasan");
		com.alpha.login.SignUp.cityBox.addItem("Gatgat");
		com.alpha.login.SignUp.cityBox.addItem("Gerrha");
		com.alpha.login.SignUp.cityBox.addItem("Ghawiyah");
		com.alpha.login.SignUp.cityBox.addItem("Hautat Sudair");
		com.alpha.login.SignUp.cityBox.addItem("Habaala");
		com.alpha.login.SignUp.cityBox.addItem("Hajrah");
		com.alpha.login.SignUp.cityBox.addItem("Haql");
		com.alpha.login.SignUp.cityBox.addItem("Harmah");
		com.alpha.login.SignUp.cityBox.addItem("Ha'il");
		com.alpha.login.SignUp.cityBox.addItem("Hotat Bani Tamim");
		com.alpha.login.SignUp.cityBox.addItem("Hofuf");
		com.alpha.login.SignUp.cityBox.addItem("Huraymila");
		com.alpha.login.SignUp.cityBox.addItem("Hafr Al-Batin");
		com.alpha.login.SignUp.cityBox.addItem("Jabal Umm al");
		com.alpha.login.SignUp.cityBox.addItem("Ru'us");
		com.alpha.login.SignUp.cityBox.addItem("Jalajil");
		com.alpha.login.SignUp.cityBox.addItem("Jeddah");
		com.alpha.login.SignUp.cityBox.addItem("Khafji");
		com.alpha.login.SignUp.cityBox.addItem("Khaybar");
		com.alpha.login.SignUp.cityBox.addItem("King Abdullah Economic City");
		com.alpha.login.SignUp.cityBox.addItem("Khamis Mushait");
		com.alpha.login.SignUp.cityBox.addItem("Knowledge Economic City, Medina");
		com.alpha.login.SignUp.cityBox.addItem("Khobar");
		com.alpha.login.SignUp.cityBox.addItem("Layla");
		com.alpha.login.SignUp.cityBox.addItem("Lihyan");
		com.alpha.login.SignUp.cityBox.addItem("Mastoorah");
		com.alpha.login.SignUp.cityBox.addItem("Medina");
		com.alpha.login.SignUp.cityBox.addItem("Mecca");
		com.alpha.login.SignUp.cityBox.addItem("Muzahmiyya");
		com.alpha.login.SignUp.cityBox.addItem("Najran");
		com.alpha.login.SignUp.cityBox.addItem("Umluj");
		com.alpha.login.SignUp.cityBox.addItem("Qadeimah");
		com.alpha.login.SignUp.cityBox.addItem("Qatif");
		com.alpha.login.SignUp.cityBox.addItem("Qaisumah");
		com.alpha.login.SignUp.cityBox.addItem("Qurayyat");
		com.alpha.login.SignUp.cityBox.addItem("Rabigh");
		com.alpha.login.SignUp.cityBox.addItem("Rafha");
		com.alpha.login.SignUp.cityBox.addItem("Ras Tanura");
		com.alpha.login.SignUp.cityBox.addItem("Riyadh");
		com.alpha.login.SignUp.cityBox.addItem("Riyadh Al-Khabra");
	
		
	}
	@SuppressWarnings("unchecked")
	public static void Qatar() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Abu Dhalouf");
		com.alpha.login.SignUp.cityBox.addItem("Abu Hamour");
		com.alpha.login.SignUp.cityBox.addItem("Abu Samra");
		com.alpha.login.SignUp.cityBox.addItem("Ain Khaled");
		com.alpha.login.SignUp.cityBox.addItem("Ain Sinan");
		com.alpha.login.SignUp.cityBox.addItem("Al Aziziya");
		com.alpha.login.SignUp.cityBox.addItem("Al Bidda");
		com.alpha.login.SignUp.cityBox.addItem("Al Daayen");
		com.alpha.login.SignUp.cityBox.addItem("Al Dafna");
		com.alpha.login.SignUp.cityBox.addItem("Ad Dawhah al Jadidah");
		com.alpha.login.SignUp.cityBox.addItem("Al Ebb");
		com.alpha.login.SignUp.cityBox.addItem("Al Egla");
		com.alpha.login.SignUp.cityBox.addItem("Al Gharrafa");
		com.alpha.login.SignUp.cityBox.addItem("Al Ghuwariyah");
		com.alpha.login.SignUp.cityBox.addItem("Al Hilal");
		com.alpha.login.SignUp.cityBox.addItem("Al Jasrah");
		com.alpha.login.SignUp.cityBox.addItem("Al Jeryan");
		com.alpha.login.SignUp.cityBox.addItem("Al Karaana");
		com.alpha.login.SignUp.cityBox.addItem("Al Kharrara");
		com.alpha.login.SignUp.cityBox.addItem("Baaya");
		com.alpha.login.SignUp.cityBox.addItem("Bani Hajer");
		com.alpha.login.SignUp.cityBox.addItem("Barahat Al Jufairi");
		com.alpha.login.SignUp.cityBox.addItem("Bu Fasseela");
		com.alpha.login.SignUp.cityBox.addItem("Bu Samra");
		com.alpha.login.SignUp.cityBox.addItem("Bu Sidra");
		com.alpha.login.SignUp.cityBox.addItem("Dahl Al Hamam");
		com.alpha.login.SignUp.cityBox.addItem("Doha International Airport");
		com.alpha.login.SignUp.cityBox.addItem("Doha Port");
		com.alpha.login.SignUp.cityBox.addItem("Duhail");
		com.alpha.login.SignUp.cityBox.addItem("Dukhan");
		com.alpha.login.SignUp.cityBox.addItem("Fuwayrit");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Abdel Aziz");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Bin Durham");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Bin Mahmoud");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Bin Omran");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Kulaib");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Mohammed Bin Jassim");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Amir");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Asiri");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Asmakh");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Murra");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Manaseer");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Nasr");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Soudan");
		com.alpha.login.SignUp.cityBox.addItem("Fereej Al Zaeem");
		com.alpha.login.SignUp.cityBox.addItem("Gharrafat Al Rayyan");
		com.alpha.login.SignUp.cityBox.addItem("Hamad Medical City");
		com.alpha.login.SignUp.cityBox.addItem("Hazm Al Markhiya");
		com.alpha.login.SignUp.cityBox.addItem("Izghawa");
		com.alpha.login.SignUp.cityBox.addItem("Jabal Thuaileb");
		com.alpha.login.SignUp.cityBox.addItem("Jelaiah");
		com.alpha.login.SignUp.cityBox.addItem("Jeryan Jenaihat");
		com.alpha.login.SignUp.cityBox.addItem("Jeryan Nejaima");
		com.alpha.login.SignUp.cityBox.addItem("Khawr al Udayd");
		com.alpha.login.SignUp.cityBox.addItem("Leabaib");
		com.alpha.login.SignUp.cityBox.addItem("Lebday");
		com.alpha.login.SignUp.cityBox.addItem("Lejbailat");
		com.alpha.login.SignUp.cityBox.addItem("Lekhwair");
		com.alpha.login.SignUp.cityBox.addItem("Leqtaifiya");
		com.alpha.login.SignUp.cityBox.addItem("Lijmiliya");
		com.alpha.login.SignUp.cityBox.addItem("Luaib");
		com.alpha.login.SignUp.cityBox.addItem("Lusail");
		com.alpha.login.SignUp.cityBox.addItem("Madinat ash Shamal");
		com.alpha.login.SignUp.cityBox.addItem("Madinat Al Kaaban");
		com.alpha.login.SignUp.cityBox.addItem("Madinat Khalifa North");
		com.alpha.login.SignUp.cityBox.addItem("Madinat Khalifa South");
		com.alpha.login.SignUp.cityBox.addItem("Mebaireek");
		com.alpha.login.SignUp.cityBox.addItem("Mehairja");
		com.alpha.login.SignUp.cityBox.addItem("Mesaieed");
		com.alpha.login.SignUp.cityBox.addItem("Mesaieed Industrial Area");
		com.alpha.login.SignUp.cityBox.addItem("Mesaimeer");
		com.alpha.login.SignUp.cityBox.addItem("Muaither");
		com.alpha.login.SignUp.cityBox.addItem("Muraikh");
		com.alpha.login.SignUp.cityBox.addItem("Mushayrib");
		com.alpha.login.SignUp.cityBox.addItem("Najma");
		com.alpha.login.SignUp.cityBox.addItem("New Al Hitmi");
		com.alpha.login.SignUp.cityBox.addItem("New Al Mirqab");
		com.alpha.login.SignUp.cityBox.addItem("New Al Rayyan");
		com.alpha.login.SignUp.cityBox.addItem("New Salata");
		com.alpha.login.SignUp.cityBox.addItem("New Fereej Al Ghanim");
		com.alpha.login.SignUp.cityBox.addItem("New Fereej Al Khulaifat");	
		com.alpha.login.SignUp.cityBox.addItem("Nu`ayjah");	
		com.alpha.login.SignUp.cityBox.addItem("Old Al Ghanim");	
		com.alpha.login.SignUp.cityBox.addItem("Onaiza");	
		com.alpha.login.SignUp.cityBox.addItem("Ras Abu Aboud");	
		com.alpha.login.SignUp.cityBox.addItem("Ras Lafan");	
		com.alpha.login.SignUp.cityBox.addItem("Rawdat Al Hamama");	
		com.alpha.login.SignUp.cityBox.addItem("Rawdat Al Khail");	
		com.alpha.login.SignUp.cityBox.addItem("Sawda Natheel");	
		com.alpha.login.SignUp.cityBox.addItem("Umm Bab");
		com.alpha.login.SignUp.cityBox.addItem("Umm Birka");
		com.alpha.login.SignUp.cityBox.addItem("Umm Ghuwailina");
		com.alpha.login.SignUp.cityBox.addItem("Umm Lekhba");
		com.alpha.login.SignUp.cityBox.addItem("Umm Qarn");
		com.alpha.login.SignUp.cityBox.addItem("Umm Salal Ali");
		com.alpha.login.SignUp.cityBox.addItem("Wadi Al Banat");
		com.alpha.login.SignUp.cityBox.addItem("Wadi Al Sail");
		com.alpha.login.SignUp.cityBox.addItem("Wadi Lusail");
		
	}
	@SuppressWarnings("unchecked")
	public static void Sri_Lanka() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Ambalanthota");
		com.alpha.login.SignUp.cityBox.addItem("Akmeemana");
		com.alpha.login.SignUp.cityBox.addItem("Akuressa");
		com.alpha.login.SignUp.cityBox.addItem("Ambalangoda");
		com.alpha.login.SignUp.cityBox.addItem("Akurana");
		com.alpha.login.SignUp.cityBox.addItem("Ambagamuwa");
		com.alpha.login.SignUp.cityBox.addItem("Alayadiwembu");
		com.alpha.login.SignUp.cityBox.addItem("Arachchikattuwa PS");
		com.alpha.login.SignUp.cityBox.addItem("Agalawatta");
		com.alpha.login.SignUp.cityBox.addItem("Alawwa");
		com.alpha.login.SignUp.cityBox.addItem("Ayagama");
		com.alpha.login.SignUp.cityBox.addItem("Ampara");
		com.alpha.login.SignUp.cityBox.addItem("Attanagalla");
		com.alpha.login.SignUp.cityBox.addItem("Angunakolapelessa");
		com.alpha.login.SignUp.cityBox.addItem("Akkaraipattu");
		com.alpha.login.SignUp.cityBox.addItem("Ambanganga Korale");
		com.alpha.login.SignUp.cityBox.addItem("Benthota");
		com.alpha.login.SignUp.cityBox.addItem("Buttala");
		com.alpha.login.SignUp.cityBox.addItem("Beliatta");
		com.alpha.login.SignUp.cityBox.addItem("Bope-Poddala");
		com.alpha.login.SignUp.cityBox.addItem("Beruwala");
		com.alpha.login.SignUp.cityBox.addItem("Bandarawela");
		com.alpha.login.SignUp.cityBox.addItem("Baddegama");
		com.alpha.login.SignUp.cityBox.addItem("Balapitiya");
		com.alpha.login.SignUp.cityBox.addItem("Badulla");
		com.alpha.login.SignUp.cityBox.addItem("Bandaragama");
		com.alpha.login.SignUp.cityBox.addItem("Balangoda");
		com.alpha.login.SignUp.cityBox.addItem("Biyagama");
		com.alpha.login.SignUp.cityBox.addItem("Colombo");
		com.alpha.login.SignUp.cityBox.addItem("Chilaw");
		com.alpha.login.SignUp.cityBox.addItem("Dankotuwa");
		com.alpha.login.SignUp.cityBox.addItem("Dimbulagala");
		com.alpha.login.SignUp.cityBox.addItem("Doluwa");
		com.alpha.login.SignUp.cityBox.addItem("Divulapitiya");
		com.alpha.login.SignUp.cityBox.addItem("Dambulla");
		com.alpha.login.SignUp.cityBox.addItem("Embilipitiya");
		com.alpha.login.SignUp.cityBox.addItem("Eravur Town");
		com.alpha.login.SignUp.cityBox.addItem("Ella");
		com.alpha.login.SignUp.cityBox.addItem("Ganga Ihala Korale");
		com.alpha.login.SignUp.cityBox.addItem("Galgamuwa");
		com.alpha.login.SignUp.cityBox.addItem("Galle");
		com.alpha.login.SignUp.cityBox.addItem("Harispattuwa");
		com.alpha.login.SignUp.cityBox.addItem("Hatharaliyadda");
		com.alpha.login.SignUp.cityBox.addItem("Imaduwa");
		com.alpha.login.SignUp.cityBox.addItem("Imbulpe");
		com.alpha.login.SignUp.cityBox.addItem("Jaffna");
		com.alpha.login.SignUp.cityBox.addItem("Ja-Ela");
		com.alpha.login.SignUp.cityBox.addItem("Katana");
		com.alpha.login.SignUp.cityBox.addItem("Kalutara");
		com.alpha.login.SignUp.cityBox.addItem("Kaduwela");
		
	}
	@SuppressWarnings("unchecked")
	public static void city_Itali() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Rome");
		com.alpha.login.SignUp.cityBox.addItem("Milan");
		com.alpha.login.SignUp.cityBox.addItem("Naples");
		com.alpha.login.SignUp.cityBox.addItem("Turin");
		com.alpha.login.SignUp.cityBox.addItem("Palermo");
		com.alpha.login.SignUp.cityBox.addItem("Genoa");
		com.alpha.login.SignUp.cityBox.addItem("Bologna");
		com.alpha.login.SignUp.cityBox.addItem("Florence");
		com.alpha.login.SignUp.cityBox.addItem("Bari");
		com.alpha.login.SignUp.cityBox.addItem("Catania");
		com.alpha.login.SignUp.cityBox.addItem("Verona");
		com.alpha.login.SignUp.cityBox.addItem("Venice");
		com.alpha.login.SignUp.cityBox.addItem("Messina");
		com.alpha.login.SignUp.cityBox.addItem("Padua");
		com.alpha.login.SignUp.cityBox.addItem("Trieste");
		com.alpha.login.SignUp.cityBox.addItem("Brescia");
		com.alpha.login.SignUp.cityBox.addItem("Parma");
		com.alpha.login.SignUp.cityBox.addItem("Taranto");
		com.alpha.login.SignUp.cityBox.addItem("Prato");
		com.alpha.login.SignUp.cityBox.addItem("Modena");
		com.alpha.login.SignUp.cityBox.addItem("Reggio Calabria");
		com.alpha.login.SignUp.cityBox.addItem("Reggio Emilia");
		com.alpha.login.SignUp.cityBox.addItem("Perugia");
		
		
	}
	@SuppressWarnings("unchecked")
	public static void city_SouthKorea() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Seoul");
		com.alpha.login.SignUp.cityBox.addItem("Busan");
		com.alpha.login.SignUp.cityBox.addItem("Incheon");
		com.alpha.login.SignUp.cityBox.addItem("Daegu");
		com.alpha.login.SignUp.cityBox.addItem("Daejeon");
		com.alpha.login.SignUp.cityBox.addItem("Gwangju");
		com.alpha.login.SignUp.cityBox.addItem("Suwon");
		com.alpha.login.SignUp.cityBox.addItem("Ulsan");
		com.alpha.login.SignUp.cityBox.addItem("Goyang");
		com.alpha.login.SignUp.cityBox.addItem("Yongin");
		com.alpha.login.SignUp.cityBox.addItem("Seongnam");
		com.alpha.login.SignUp.cityBox.addItem("Bucheon");
		com.alpha.login.SignUp.cityBox.addItem("Ansan");
		com.alpha.login.SignUp.cityBox.addItem("Jeonju");
		com.alpha.login.SignUp.cityBox.addItem("Cheonan");
		com.alpha.login.SignUp.cityBox.addItem("Namyangju");
		com.alpha.login.SignUp.cityBox.addItem("Anyang");
		com.alpha.login.SignUp.cityBox.addItem("Gimhae");
		com.alpha.login.SignUp.cityBox.addItem("Pohang");
		com.alpha.login.SignUp.cityBox.addItem("Pyeongtaek");
		com.alpha.login.SignUp.cityBox.addItem("Siheung");
		com.alpha.login.SignUp.cityBox.addItem("Uijeongbu");
		com.alpha.login.SignUp.cityBox.addItem("Gumi");
		com.alpha.login.SignUp.cityBox.addItem("Paju");
		com.alpha.login.SignUp.cityBox.addItem("Gimpo");
		
	}
	@SuppressWarnings("unchecked")
	public static void city_France() {
		com.alpha.login.SignUp.cityBox.removeAllItems();
		com.alpha.login.SignUp.cityBox.addItem("Paris");
		com.alpha.login.SignUp.cityBox.addItem("Marseille");
		com.alpha.login.SignUp.cityBox.addItem("Lyon");
		com.alpha.login.SignUp.cityBox.addItem("Toulouse");
		com.alpha.login.SignUp.cityBox.addItem("Nice");
		com.alpha.login.SignUp.cityBox.addItem("Nantes");
		com.alpha.login.SignUp.cityBox.addItem("Strasbourg");
		com.alpha.login.SignUp.cityBox.addItem("Montpellier");
		com.alpha.login.SignUp.cityBox.addItem("Bordeaux");
		com.alpha.login.SignUp.cityBox.addItem("Lille");
		com.alpha.login.SignUp.cityBox.addItem("Rennes");
		com.alpha.login.SignUp.cityBox.addItem("Reims");
		com.alpha.login.SignUp.cityBox.addItem("Le Havre");
		com.alpha.login.SignUp.cityBox.addItem("Saint-Étienne");
		com.alpha.login.SignUp.cityBox.addItem("Toulon");
		com.alpha.login.SignUp.cityBox.addItem("Grenoble");
		com.alpha.login.SignUp.cityBox.addItem("Dijon");
		com.alpha.login.SignUp.cityBox.addItem("Nîmes");
		com.alpha.login.SignUp.cityBox.addItem("Angers");
		com.alpha.login.SignUp.cityBox.addItem("Villeurbanne");
		com.alpha.login.SignUp.cityBox.addItem("Le Mans");
		com.alpha.login.SignUp.cityBox.addItem("Saint-Denis");
		com.alpha.login.SignUp.cityBox.addItem("Aix-en-Provence");
		
		
	}
}